### ISSUE TITLE
Open window flicker because of compatibility of other plugin.

### ISSUE THREAD

**Issue by kevinhwang91** [neoclide/coc.nvim#1340]
https://github.com/rbong is a plugin like git log.

I reported an issue at https://github.com/rbong/vim-flog/issues/21

The author of vim-flog said that it is caused by coc redrawing when open windows.

I like both plugins features, have a workaround to make them compatible?

**Comment by oblitum** [comment]
Did you use master branch like pointed in that issue?

**Comment by oblitum** [comment]
Although I think current release is updated with master.

**Comment by kevinhwang91** [comment]
> Did you use master branch like pointed in that issue?

Using`Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}`, the result is the same with the branch of release.

**Comment by chemzqm** [comment]
I think vim-flog should fix this kind of issue by reuse exist window instead.

**Comment by rbong** [comment]
@chemzqm not always possible from our side since we're a fugitive extension, fugitive would need a way to reuse a window which they probably won't do. At some point coc redrawing directly or indirectly after closing a window. It should be possible for a user or plugin script to close a window and open another window without flickering, sometimes this is intrinsically impossible to avoid such as if they wish to open a preview window or list window or terminal window. If at all possible it would be good if coc didn't redraw, but I understand if that's not possible for one reason or another, I just don't have the context as to why it would do so.

**Comment by rbong** [comment]
I can no longer recreate this with `Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}`, so it's possible something else is now causing it, or it doesn't happen under certain conditions.

**Comment by chemzqm** [comment]
@rbong `redraws` command was removed, so it should be fixed now.
