### ISSUE TITLE
Calculated signature help positions may be incorrect for Lisp family languages

### ISSUE THREAD

**Issue by Cnly** [neoclide/coc.nvim#1467]
## Result from CocInfo

```
vim version: NVIM v0.5.0-261-g2ef72437f
node version: v13.5.0
coc.nvim version: 0.0.74-15f685206a
term: xterm-256color
platform: linux
```

## Describe the bug

It seems that the function `triggerSignatureHelp` tries to determine the position parameter for signature help by:

https://github.com/neoclide/coc.nvim/blob/6e06c8854027fb6802409f06bf25e51d8f775729/src/handler/index.ts#L848-L849

which should work fine for most languages. But for Lisp-like languages, this may be problematic. For example, in the following scenario, the position will be incorrect:

```clojure
(outer-func param-a param-b (inner-func param-1 param-2) |)
 ^                           ^                           ^
 |                           |                           Cursor
 |                           coc.nvim will send the position of this character
 Actual function whose parameters are being filled in
```

## Reproduce the bug

I found this behaviour when I'm trying to implement the signature help function for [clojure-lsp](https://github.com/snoe/clojure-lsp), and I think the reproduction steps aren't really necessary because this can be seen in the code? But if this is indeed a non-existing problem or I've missed something somewhere, please kindly tell me.

**Comment by Cnly** [comment]
@chemzqm What do you think about simply sending the actual cursor position?

**Comment by chemzqm** [comment]
> What do you think about simply sending the actual cursor position?

@Cnly We send actual cursor position at first, but it turns out some language servers like ccls would not work.

**Comment by pappasam** [comment]
Sending the actual cursor position every time sounds like the more-correct approach to me. The current behavior basically introduces a bug for well-designed language servers because of bugs (or bizarre language-specific edge cases) associated with "some" language servers (like ccls).

Check out this bad behavior when I set my editor to trigger signature help on cursor hold in `Python` code using https://github.com/pappasam/jedi-language-server:

```vim
  autocmd CursorHold * call CocActionAsync('showSignatureHelp')
  autocmd CursorHoldI * call CocActionAsync('showSignatureHelp')
```

![bad-signature](https://user-images.githubusercontent.com/3723671/80619869-48e1f100-8a13-11ea-82af-9b4100d619e0.gif)

I'm using a custom language server that I've written, so I'm also printing the cursor position sent by Coc.

## Solutions

1. Send the actual cursor position every time OR
2. Support both options (actual position OR whatever's being sent now) and make this configurable

**Comment by pappasam** [comment]
Note: I've tested locally, and simply commenting out this line completely fixes the problem for me:

https://github.com/neoclide/coc.nvim/blob/master/src/handler/index.ts#L880

At the very least, this is where we can add the option to disable the mutation of cursor postion. At best, this is what we can remove entirely from Coc.

**Comment by chemzqm** [comment]
Agreed.
