### ISSUE TITLE
<C-H> <C-L> in completion

### ISSUE THREAD

**Issue by mk-boop** [neoclide/coc.nvim#1481]
I do manipulate omnicompletion results with `<C-L>` and `<C-H>`. I found there is no such method for CoC completion. Would be nice to implement those in Coc as described in `|ins-completion-menu|`
Cheers

**Comment by fannheyward** [comment]
Did I misunderstand your issue? `<C-H>` and `<C-L>` is working in default: `<C-H>` to delete a character before current cursor, and `<C-X C-L>` completes from lines.

**Comment by mk-boop** [comment]
When the popup with suggestions is up:

_Omnicompletion_ behaviour: `<C-H>` is expanding on the number of suggestions in the popup (as the term gets general). `<C-L>` reduces the number of suggestions as term gets more specific. Both happen without re-issuing code completion shortcut.

_Coc.vim_  behaviour:  `<C-H>` cancels the popup (need to re-issue completion keystroke to continue with completions). `<C-L>` all is doing is writing `^L` string to the buffer.

I wish Coc.vim behave more like omnicompletion in that matter cause its very useful and intuitive.
Unless I'm experiencing a bug or missconfiguration. Cheers.

**Comment by fannheyward** [comment]
Got it. I'll check this whether is possible.

**Comment by chemzqm** [comment]
You can configure your keymap for specific completion source, you should just use completion provided by vim instead of wish coc.nvim which is an async completion engine to do that.

**Comment by kmoschcau** [comment]
Hi, this sounds to me like there was a misunderstanding on what `<C-H>` and `<C-L>` actually do in Vim. This is not about a completion source. (`<C-X> <C-L>` is to start completing whole lines) I would very much like to have this feature as well, that's why I am trying to clear up this misunderstanding.
The relevant help entry in vim is `popupmenu-keys`. What those two keys do when a popup menu is open is basically this:
- `<C-H>`/`<BS>`: delete the character before the cursor and update the completion list (both of these keys already work with coc.nvim)
- `<C-L>`: insert the next character of the current match and update the completion list (this does not work with coc completion menus and instead just inserts the `^L` control character into the buffer)
If this is already possible with coc and just needs to be configured properly, can you please point it out to me where this needs to be done? Otherwise if it is not currently possible, could you please have a look at implementing it?

Thank you.

**Comment by chemzqm** [comment]
> `<C-L>`: insert the next character of the current match and update the completion list

Don't know how to make it work with or without coc.nvim :(

**Comment by kmoschcau** [comment]
For getting it to work without coc.nvim, you have to know how to select items in the completion list without inserting it. You do that by using the arrow keys, instead of `<C-N>` and `<C-P>`. When you then have an item selected, you can press `<C-L>` and Vim will insert the next character after what you have already typed of that item into the buffer.

Also your `'completeopt'` has to include `noselect` and maybe even `noinsert`.

I also tried it some more and noticed that it is actually working with coc.nvim to some extent.
When you first select an item with the arrow keys with coc.nvim, `<C-L>` works as expected. If you don't then it just inserts `^L` into the buffer. With Vim's native completion it always works no matter whether an item is selected or not. If none is selected, it just uses the first one.
Another situation where it breaks with coc.nvim is when the character to insert is not a keyword character. For example when you reached the end of a function name and the next character is the opening parameter parenthesis.

I hope that helps. If you need some more info, feel free to ask. Also I could record an asciinema, if that helps.

**Comment by kmoschcau** [comment]
I just checked, `i_CTRL-L` is not bound to anything for me. I also had a look at the help entry you posted and I didn't really find any setting that seemed related. The only thing I changed was the `"suggest.keepCompleteopt"` setting (I changed it to true, because my `'completeopt'` is already set up properly), but that didn't change the current behavior. What exactly do you suggest I should change?

**Comment by chemzqm** [comment]
It does the insert, but not filter, since coc.nvim detect latest typed character for filter.

**Comment by kmoschcau** [comment]
Yes I noticed that as well. The character is inserted, but the list is not updated when using `<C-L>`.

**Comment by kmoschcau** [comment]
Sorry it took so long to try this, but yeah just calling coc#refresh() afterwards does indeed work. However it doesn't fix the issue that `^L` is inserted into the buffer, if you don't select an item with the arrow keys first.
