### ISSUE TITLE
Interaction with direnv

### ISSUE THREAD

**Issue by patrl** [neoclide/coc.nvim#1493]
**Is your feature request related to a problem? Please describe.**

I use the [nix package manager](https://nixos.org/nix/) to create a development environment with the tools and dependencies I need on a per-project basis, including lsp implementations such as `ghcide` for haskell. I use `direnv`, and the [direnv.vim](https://github.com/direnv/direnv.vim) plugin to automatically load the environment from nix-shell upon entering a directory with a `shell.nix` file. This is a relatively common workflow for users of nix.

`coc.vim` in general integrates nicely with this workflow -- the only pain-point is that I have to invoke `:CocRestart` to get coc to recognise the environment set by `direnv.vim`. It seems that coc starts too quickly, or conversely direnv sets the environment too late.

**Describe the solution you'd like**

Detect the presence of an `.envrc` file; if present, defer loading coc until after `direnv.vim` has set the environment.

**Comment by oblitum** [comment]
@patrl I think this is not responsibility of any plugin to wait for others, it's user's responsibility to set whatever loading order it needs. You may be hitting this issue because for some random reason coc.nvim will load before than dirven, but if you're not controlling such order yourself, it's expected that order won't matter, so for some other people the reverse may happen.

If you use VIM-PLUG I just recommend you to lazy load coc.nvim.

**Comment by patrl** [comment]
@oblitum OK, I think that's fair. I don't use (or plan on using) vim-plug. Is there an alternative method to defer loading of coc.nvim?

**Comment by oblitum** [comment]
@patrl I don't have experience with lazy loading expect for vim-plug. This article may be of help regarding loading order: https://vimways.org/2018/from-vimrc-to-vim/

**Comment by patrl** [comment]
Thanks for the information. I’ll continue to experiment. It’s a shame there isn’t a clear solution that isn’t dependent on a particular plugin manager. I’ll go ahead and close this issue.

**Comment by oblitum** [comment]
FYI, from `direnv.vim` README: "[snip] Direnv will be fired only on `VimEnter` [snip] and on `DirChanged`". This means the plugin core is actually triggered much later than plugin loading. There's really no solution by plugin `rtp` order. You'll need to do something clever to have `direnv.vim` loaded before any plugin.

Here's a possible solution: after you have imported `direnv.vim`, create a `VimEnter` `autocmd`, and load coc.nvim from it. This `autocmd` should be register later than the `direnv.vim` `VimEnter` `autocmd`.

**Comment by oblitum** [comment]
FWIW, I'm not sure whether it's OK to load coc.nvim from a `VimEnter` `autocmd`.

**Comment by liferooter** [comment]
All Lua-based and Vimscript-based plugins work perfectly with `direnv.vim`, but `coc.nvim` doesn't. That's because they use NeoVim's environment variables controlled by `direnv.nvim`. Unfortunately, `coc.nvim` doesn't use them automatically because of separate Node.js process that has different environment. This behavior breaks any features that require environment updates of NeoVim. I suggest to load the environment from NeoVim just before start of LSP. This will fix the issue without hacks and workarounds by solving fundamental problem that cause it.
