### ISSUE TITLE
coc-references as a popup/floating window?

### ISSUE THREAD

**Issue by davidv171** [neoclide/coc.nvim#1586]
**Is your feature request related to a problem? Please describe.**
The current default behavior of coc-references is a DOUBLE split. One for preview and one for the actual usages/references.

**Describe the solution you'd like**
Using the floating/popup window would suit it a lot better, in my opinion. It can use a preview to the right, much like FZF.vim(screenshot below):

**Describe alternatives you've considered**
I've tried just living with it, and it is usable, but at least having the option to use floating for this would be great.

**Additional context**
![image](https://user-images.githubusercontent.com/26347830/75390909-71515000-58e9-11ea-83cd-f8fa94eddd4f.png)

**Comment by chemzqm** [comment]
FZF use terminal buffer which makes create float window much easier.
There would be lots of problems like handling cursor, key-mapping, switch between normal and insert mode, resume feature if we use float window for coc list.
IMO, the float window does looks better, but we don't want to use terminal buffer since we will miss many useful features.

**Comment by davidv171** [comment]
Okay makes sense. I did not consider this angle at all.

**Comment by chemzqm** [comment]
Try https://github.com/antoinemadec/coc-fzf if you're using fzf.
