### ISSUE TITLE
Allow snippet and completion candidates that have same name

### ISSUE THREAD

**Issue by sandangel** [neoclide/coc.nvim#171]
**Describe the bug**
In many cases, I'd like to use completion candidate as it is, not expand as a snippet.

For example, when I want to import a function, I only want the function name when I hit accept completion. but coc expand the function to its signature.
 
**To Reproduce**
create a `.ts` file, import some function from node library like `import { strictEqual } from 'assert'`
strictEqual will be expanded to its function signature.

**Expected behavior**

Provide both options: name of the function only candidate, and a snippet candidate
in the completion popup menu.

**Screenshots**
![nov-24-2018 10-13-16](https://user-images.githubusercontent.com/22189661/48963230-9f066580-efd1-11e8-9794-a4df6869e637.gif)

**Desktop (please complete the following information):**
 - Terminal: all

**Additional context**

**Comment by oblitum** [comment]
Currently I set `"coc.preferences.triggerSignatureHelp": false` in my `coc-settings.json`, to not have snippets by default, this has been discussed before at https://github.com/neoclide/coc.nvim/issues/156#issuecomment-437949699.

**Comment by oblitum** [comment]
With that setting I can chose to expand snippets or not upon menu confirmation, `<c-y>` by default.

**Comment by chemzqm** [comment]
> I only want the function name when I hit accept completion. but coc expand the function to its signature.

That's why `noselect` is enabled by default, so you can insert function name by `<C-n>` and trigger completion if get snippet expanded.

Another issue is if you use `<up>` and `<down>` to select complete item, coc would unable to detect which item is selected, so no completion resolve request would be called.

The problem could be resolve by improve coc-tsserver, it could not return function snippet on `import` of `require` statement.

**Comment by chemzqm** [comment]
It's fixed with coc-tsserver 1.1.15
