### ISSUE TITLE
Add an option to suppress Vim error messages

### ISSUE THREAD

**Issue by BojanStipic** [neoclide/coc.nvim#1715]
First of all, thank you very much for creating this fantastic plugin. It really is the best LSP client, in my opinion. I just have one small issue, described bellow.

**Is your feature request related to a problem? Please describe.**
I would like to have an option to suppress Vim error messages that get echoed when LSP server returns an error.

For example, I want to test something quickly, so I open up Vim:

```
$ vim main.rs
```

Now, because I have a LSP server for Rust, and I haven't created a proper Cargo project, I get this ugly error message:

```
[coc.nvim]rust-analyzer failed to load workspace: Failed to find Cargo.toml for 
path /home/bojan
Caused by:
    can't find Cargo.toml at /home/bojan, due to no Cargo.toml file found
Press ENTER or type command to continue
```

**Describe the solution you'd like**
It would be great if it was possible to configure Coc to just let LSP server silently fail, and not give me any visible error messages.
Can you please add such option?

**Describe alternatives you've considered**
I would go as far to say that this should even be a default behavior.

If a LSP cannot be started, it is probably because user purposefully didn't create a proper project, and just wants to do a quick test.
If a user really has a problem with LSP starting, they can just run `:CocInfo` to debug the problem anyway.

I think this way, Coc would provide a better user experience.

**Additional context**

Screenshot of the mentioned error message:
![image](https://user-images.githubusercontent.com/13490088/78395952-fbbe5b00-75dd-11ea-912a-ae589293c1c8.png)

**Comment by dseeni** [comment]
![image](https://user-images.githubusercontent.com/6591429/78403127-b6cfff80-75b0-11ea-9e38-e5297575258c.png)

oh god how do I make it stop

**Comment by chemzqm** [comment]
@daern91 use vim with float window support

**Comment by monofon** [comment]
I second that! Being able to silence that error message would really be helpful. Especially if working with buggy language servers.

**Comment by chemzqm** [comment]
No, we can't provide option to disable error message, send your feature request to that language server to disable that message instead.

**Comment by chemzqm** [comment]
You can hack this function https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/util.vim#L266 if you want to.

**Comment by phongvcao** [comment]
@chemzqm there are messages that aren't necessary due to LSP. One thing I think would really help is adding an option to display the message on just 1 line - or somehow abbreviate the message. I believe YCM has option to completely disable this type of message, but I understand your concern. However, sometimes the message displayed are super annoying, getting in the way of our workflows and yet we have to wait for another party to fix the message. Hence if possible, can you add an option to display these messages in 1 line? Or abbreviate the message with "..."? We just need to know there's an error - we don't need to read the full error (we would open CocInfo for that anyway).

**Comment by chemzqm** [comment]
No, the error messages comes from code of coc.nvim or it's extensions, you have to see them.
We will use float window for better experience in the feature.
