### ISSUE TITLE
[coc] server connection lost

### ISSUE THREAD

**Issue by andradei** [neoclide/coc.nvim#1830]
## Result from CocInfo

Error: Node version  < 8.10.0, please upgrade node.js

## Describe the bug

I have only one installation of node, which is version 14.0.0, installed via `sudo snap install node --channel=14/stable --classic`

## Reproduce the bug

- Install `nvim` snap package
- Install `node` snap package
- Install coc-vim via vim-plug
- Open `nvim` and get the error

- with mini.vim
  - `:CocList` doesn't show anything
  - `:messages` still show `[coc] server connection lost`

## Note

Running `sudo nvim` makes it find `node` but the other plugins are not found.

**Comment by chemzqm** [comment]
Use `g:coc_node_path`

**Comment by andradei** [comment]
I did but no same error.

```
$ which node
/snap/bin/node
```

in `init.vim`

```
let g:coc_node_path = 'snap/bin/node'
```

Still the same problem.

**Comment by oblitum** [comment]
@andradei you're not using absolute path above.

**Comment by andradei** [comment]
That was a typo. Edited.

**Comment by andradei** [comment]
I uninstalled nvim and node from snap and installed them from source.
It works now.

**Comment by fikrinzf** [comment]
> I uninstalled nvim and node from snap and installed them from source. It works now.

Thanks man, its work on me.

**Comment by BlackLight** [comment]
I know it's an old issue, but I bumped into this problem again with the neovim snap installation.

It seems that the snap installation wants the `node` executable to be under `/snap/bin` as well - snap sandbox constraints I would speculate, although the `python3` integration doesn't seem to be affected by this issue.

Setting `g:coc_node_path` to the system-installed `node` didn't work, but symlinking does:

```shell
[sudo] ln -s /usr/bin/node /snap/bin
```

Of course, this requires `node` to be natively installed on the system, not via snap.

**Comment by still-dreaming-1** [comment]
I don't understand, the solution is that it doesn't work? You can't use snap to install neovim and node and then use coc.nvim with them? You can only install them from source?

**Comment by KoBruhh** [comment]
I have reinstalled it from source nothing has been changed. Only thing that I changed was my OS and my WM

**Comment by KoBruhh** [comment]
I fixed it!
I did try yarn installation method. (I installed yarn I did not had it before)
I reinstalled Coc-nvim and node

**Comment by BlackLight** [comment]
Ok, I'm now stuck on Ubuntu LTS on my work laptop and using the Snap versions of nvim and node is the only option - those apt packages are quite ancient.

Now that symlinking the system `node` inside of the Snap bin folder is no longer an option, I've really run out of ideas.

What's weird is that `node --version` gives _no output_ whatsoever even when I run it in my session:

```vim
let output = trim(system('/snap/bin/node --version'))
echomsg output
" Empty string
```

While _any_ other command outputs something.

I thought that the version may be printed on the stderr instead of stdout on the Snap version, but even a `2>&1` redirect still gives an empty string.

Everything seems to work in the terminal though:

```bash
❯ out=$(node --version)
❯ echo $out
v20.11.1
```

So I'm really not sure anymore of where the problem is - if it's the Snap version of node that doesn't handle output piping to nvim properly, or the Snap version of nvim that doesn't read properly from the pipe.

Just in case, is there a bug report on the node Snap package to keep track of this issue?

**Comment by fannheyward** [comment]
Properly a Snap's issue.

**Comment by xieshiyao** [comment]
I ran into the same problem and solved it by removing the snap `node` and installing it using `nvm` (Node Version Manager).

1. Install `nvm`
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
```
2. Activate `nvm`
```
source ~/.bashrc
```
3. Install `node`
```
nvm install --lts
```
 (This install LTS version. See other available versions by using `nvm ls-remote`)
