### ISSUE TITLE
border for floating help / error windows

### ISSUE THREAD

**Issue by jack-faller** [neoclide/coc.nvim#1998]
**Is your feature request related to a problem? Please describe.**
having a colored rectangle popup looks really ugly against a transparent terminal background. If I set it to transparent you can't see the edges.

**Describe the solution you'd like**
a boolean to set some Unicode glyphs around the edges of floating help/error windows. eg 
```
╭─────╮
│ err │
╰─────╯
```
**Describe alternatives you've considered**
just living with it looking bad

**Additional context**
![image](https://user-images.githubusercontent.com/63514213/83079147-b6ad2700-a06a-11ea-8507-76707154b84f.png)

**Comment by chemzqm** [comment]
Neovim doesn't support border, so we will not waste time on that, you can hack the code if you're using vim8 only.

**Comment by jack-faller** [comment]
but how can you put text in the box but not "│", why does that only work in vim8? it's just putting two characters at the end of each line they work fine on my indent guide plugin.

**Comment by chemzqm** [comment]
Not that simple

**Comment by jack-faller** [comment]
@chemzqm it looks simple here https://github.com/neovim/neovim/issues/9718#issuecomment-546603628

**Comment by oblitum** [comment]
@jack-faller then write a pull for review, few people care for this.

**Comment by chemzqm** [comment]
@jack-faller no, it's broken when content is scrollable.

**Comment by oblitum** [comment]
NeoVim now supports borders (`:h nvim_open_win`). Would be nice to have an option for it now?

**Comment by chemzqm** [comment]
We could support border and border highlight since 0.0.80, but I don't think add those configuration would be necessary, you can change options at
https://github.com/neoclide/coc.nvim/blob/fb123ed9892873e32ea5eaeb480e88821c98dadf/src/diagnostic/manager.ts#L474
https://github.com/neoclide/coc.nvim/blob/fb123ed9892873e32ea5eaeb480e88821c98dadf/src/handler/hover.ts#L117
https://github.com/neoclide/coc.nvim/blob/fb123ed9892873e32ea5eaeb480e88821c98dadf/src/handler/signature.ts#L216

**Comment by oblitum** [comment]
Thanks for info, though that isn't a great route for release branch users, and updates would overwrite local patches.
