### ISSUE TITLE
Please add a rationale / comparison with competing plugins to README

### ISSUE THREAD

**Issue by dkvasnicka** [neoclide/coc.nvim#204]
**Is your feature request related to a problem? Please describe.**
I don't know if I should invest the time to set this all up when I recently started using Deoplete.

**Describe the solution you'd like**
I'd like a clean and concise rationale / "sales pitch" section in the README and ideally also comparison to other plugins serving the same purpose (Deoplete, YCM, etc.)

**Comment by oblitum** [comment]
IMO, there's no replacement to that than trying it out. A "sales pitch" over others can even be worse since it can be misleading on your POV when you finally put it to test and may or may not find issues, even more at this 0.x state.

I've left YCM myself for Coc around a few days back and experimented with others, I chosed it because of development activity, and I've used that to report a lot :)

**Comment by oblitum** [comment]
YCM had a "sales pitch" over clang_complete sounding like deprecating it, but it has always missed features from clang_complete, like signature help, so it was frustrating to read it was much better and then when trying veryfing it missed features.
