### ISSUE TITLE
[IMPORTANT] Stop fund this project on bountysource.com

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#2146]
Thank you, sponsors of coc.nvim.  We have decided to remove this project from [bountysource.com](https://salt.bountysource.com/teams/coc-nvim) at mid of July, if you have enabled monthly support, please stop it by visit https://salt.bountysource.com/teams/coc-nvim

https://news.ycombinator.com/item?id=23551098

The project will be continued, and we will find out a new way to fund the project :)

**Comment by WhyNotHugo** [comment]
Hi! I'd like to send you money since you're doing a great job working on tools that make my life easier every day.

Have you though of signing up to something like [GitHub Sponsors](https://github.com/sponsors)?

**Comment by OkanEsen** [comment]
> Hi! I'd like to send you money since you're doing a great job working on tools that make my life easier every day.
> 
> Have you though of signing up to something like [GitHub Sponsors](https://github.com/sponsors)?

Github Sponsors won't work, because @chemzqm is from China.

See: https://github.com/neoclide/coc.nvim/issues/1695#issuecomment-605763307

But I aggree, an alternative to Paypal/Patreon would be great. Maybe Liberapay as an alternative to Bountysource could work, though I don't know if it's available in China?

**Comment by WhyNotHugo** [comment]
I see there's a "sponsor" button at the top now pointing users to the right place. Nice! :)
