### ISSUE TITLE
Cannot run the installer on Ubuntu Server

### ISSUE THREAD

**Issue by tbrodbeck** [neoclide/coc.nvim#2169]
#1938  Describe the bug
```
➜  ~  curl -sL install-node.now.sh/lts | zsh      
  Configuration
> Version:  v12.18.2 (resolved from lts)
> Prefix:   /usr/local
> Platform: linux
> Arch:     x64

> Tarball URL: https://nodejs.org/dist/v12.18.2/node-v12.18.2-linux-x64.tar.gz
! Prefix bin directory /usr/local/bin is not in your $PATH
? Install Node.js v12.18.2 to /usr/local? [yN] y
> Installing Node.js, please wait…
tar: bin/node: Cannot open: Permission denied
tar: bin/npm: Cannot open: Permission denied
tar: bin/npx: Cannot open: Permission denied
tar: bin: Cannot utime: Operation not permitted
tar: share/systemtap: Cannot mkdir: Permission denied
tar: share/systemtap: Cannot mkdir: Permission denied
tar: share/systemtap/tapset: Cannot mkdir: No such file or directory
tar: share/systemtap: Cannot mkdir: Permission denied
tar: share/systemtap/tapset/node.stp: Cannot open: No such file or directory
``` 
The same happens with `sudo curl -sL install-node.now.sh/lts | zsh`.
Am I doing something wrong?
## Reproduce the bug
Prerequesite: Ubuntu Server 20.04 LTS x86_64 and `sudo apt install nodejs`

**Comment by oblitum** [comment]
This is a system of yours, nothing related with coc.nvim. You should figure out how to install node.

**Comment by tbrodbeck** [comment]
Node is installed. I just tested it for you:
```
➜  ~ node  
> 1+1
2
```

**Comment by oblitum** [comment]
Well, you just posted an error on your  node installation on your issue report. I don't get what you want.

**Comment by tbrodbeck** [comment]
I do not want to install node, I want to install coc.vim

**Comment by oblitum** [comment]
Follow instructions in readme and when you find an error regarding coc.nvim install report, or ask first on gitter channel which is better for chat. Until now the only reports you posted are node install reports, nothing related to coc.nvim.

**Comment by chemzqm** [comment]
Unfortunately, you have to install node before use coc.nvim.

**Comment by Shellcat-Zero** [comment]
For anyone else coming here, the default install instructions for node are requiring root (sudo) privilege because it wants to install in some `/usr/local/` path at least on Ubuntu machines, which is really unfortunate, and there does not appear to be some way of changing the path when running this `curl | bash` command. Therefore, if you want to set this up without root/sudo permissions, it seems you must install node with `nvm` as documented [here](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-18-04).

I would strongly suggest providing some install instructions that do not require root/sudo permission.

**Comment by oblitum** [comment]
@Shellcat-Zero doesn't Ubuntu have node on apt? I'm sure they have it.

**Comment by Shellcat-Zero** [comment]
@oblitum apt requires root/sudo permission, which should be unnecessary for vim configurations. A common use case for vim (just like `nano`) is on managed headless servers (lacking a GUI) where most users do not have superuser permission. The instructions, as they currently stand, are incorrect due to this omission.

It should also be noted that piping scripts directly to bash from curl without looking at them is a serious security issue, which is usually also noted elsewhere in most install docs where the procedure recommends `curl | bash` installs.

**Comment by oblitum** [comment]
@Shellcat-Zero right, but I see all that as up to node, coc can't fix them, their docs, etc.

**Comment by dlwalter** [comment]
Having to reference this issue and @Shellcat-Zero's comments to get node up and running.

> I would strongly suggest providing some install instructions that do not require root/sudo permission.

Completely agree.  The current instructions in the readme are insufficient.
