### ISSUE TITLE
auto select of first item from the drop down menu

### ISSUE THREAD

**Issue by Qwerty2o** [neoclide/coc.nvim#2221]
It may sound stupid (forgive me if it is),
but when i get a suggested completion it doesn't automatically go to that.
And it just bothers me when there's only one good suggestion or I need the first one and I need to press the down key and only then am I able to choose the first and wanted completion.
What I want it to be is like in vscode where you start a word, the menu opens up but the first result it automatically pointed at, so i can just press enter and it completes my word.
Again sorry if it sounds silly or if it's something that's already customizable/ I don't do right and i just don't know it.
Thanks for the hard work.

**Comment by chemzqm** [comment]
Checkout `:h coc-config-suggest`

**Comment by chemzqm** [comment]
There's also function provided to select first complete item when no items selected

**Comment by oblitum** [comment]
Duplicate of #2058. I've posted a mapping for this there.

**Comment by Qwerty2o** [comment]
i didnt quite understood how to use that function or that mapping.
I saw suggest.noselect that is set to false. is that it? if so, how to i set it to true?

the mapping way was also unclear to me. where do i put it/how?

sorry, am quite new to this.

**Comment by Qwerty2o** [comment]
> Duplicate of #2058. I've posted a mapping for this there.

forgot to quote. thought maybe you won't see it
can you explain to me how to disable noselect?

**Comment by hugoruscitti** [comment]
Hi @Qwerty2o !!

I got something like what your requested by making some changes in the config.

Note that i'm not need to press keydown, i only press enter because the first option is selected.

![autocompletado](https://user-images.githubusercontent.com/99183/90326389-407bda80-df5e-11ea-998b-d432f3e94ac2.gif)

So, to archive this behaviour you need to call the :CocConfig command, and then, enter this configuration:

```
{
  "suggest.noselect": false
}
```

Btw, if you want autocomplete in this file just run the ":CocInstall coc-json" command and you will see something like this:

![image](https://user-images.githubusercontent.com/99183/90326526-93a25d00-df5f-11ea-9e0a-31d537359292.png)
