### ISSUE TITLE
Unknown function: coc#util#clear_highlights when creating any split

### ISSUE THREAD

**Issue by IJSlater** [neoclide/coc.nvim#2429]
## Result from CocInfo

 
vim version: VIM - Vi IMproved 8.2 8
node version: v14.13.0
coc.nvim version: 0.0.78-fd9e7d3972
term: dumb
platform: linux

## Describe the bug
When ever I open a new split or move between splits the following errors freeze my session for a few seconds before they go away.
```
chdir($HOME/.vim/pack/coc/start/coc.nvim-release/autoload/coc)
fchdir() to previous dir 
Error detected while processing WinLeave Autocommands for "*":
E117: Unknown function: coc#util#clear_highlights
autocommand call s:Autocmd('WinLeave', win_getid())
```
It's worth noting that this error dose not happen on my arch instillation but dose happen on my ubuntu machine. 
## Reproduce the bug

  ```vim
set hidden
set nobackup
set nowritebackup
set cmdheight=1
set updatetime=300
set shortmess+=c
 let g:coc_node_path = '~/.vim/bin/node'
let g:coc_disable_startup_warning = 1 
  ```

**Comment by chemzqm** [comment]
Reinstall coc.nvim.

**Comment by IJSlater** [comment]
I have completely deleted and reinstalled Coc a number of times, this has not helped.

**Comment by chemzqm** [comment]
Looks like you have other coc.nvim in your packages folder or `&rtp`

**Comment by louisrli** [comment]
I also started running into this after updating coc.nvim after a while of not updating. Could you clarify what you mean by "you have `&rtp`? I've double-checked that there's no other coc.nvim

**Comment by Njiallu** [comment]
Hey @louisrli . I post this for posterity because I've encountered this issue multiple times on some of my installs.

I believe that if you want to fully remove `coc` from your `vim-plug` install you should remove these locations:
- `~/.config/nvim/pack/neoclide-coc.nvim`
- PATH TO PUGGED`/coc.nvim`

And if you want to wipe the config of coc you can also remove:
- `~/.config/coc`

PS: `PATH TO PLUGGED` is the directory you set here in the vim plug call:
`call plug#begin(expand('~/.local/share/nvim/plugged'))`

**Comment by chemzqm** [comment]
The error stacks is improved on latest coc.nvim, so you can see how it's caused by check the log.
