### ISSUE TITLE
Make notification in float window less disturbing.

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#2702]
Compare to statusline progress, user could cancel the action with progress window by simply close it, but current notification window could be annoying.

Create a small window without border at right bottom region of screen seems better.

**Comment by fannheyward** [comment]
VSCode's `withProgress` support location, which controls the notification window position.

**Comment by gerardabello** [comment]
In addition to being annoying, it prevents seeing completion docs (the documentation modal that appears next to the completion list) when using C-n to browse through the completions, at least in rust-analyzer:
- C-n moves to next completion (showing also the documentation), and also changes the buffer.
- Changing the buffer makes rust-analyzer index the file again (showing the floating window).
- When the floating window closes, after a fraction of a second, the documentation also closes.

It does not happen with the arrow keys, as they move through the completion list but does not change the buffer.

workspace.progressTarget to statusline solves it.

**Comment by MonliH** [comment]
Yes, this feature is especially annoying when `diagnostic.refreshOnInsertMode` is on. Every time I press a key, the notification from the rust analyzer pops up then disappears.

**Comment by GopherJ** [comment]
this becomes quite annoying while coding rust, since rust-analyzer reports also `build-script-fail`

https://github.com/rust-analyzer/rust-analyzer/issues/9096

**Comment by GopherJ** [comment]
hi, is there any news around this? in rust it can be very disturbing as you can see from the following:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/33961674/125585399-ef40ec35-8404-458d-a9e0-e9cec4ba4d2b.png">

when the build script fails, it gives a notification, also it never stops... it keeps giving this notification every a few seconds

**Comment by GopherJ** [comment]
A crazy one can be like:

<img width="529" alt="image" src="https://user-images.githubusercontent.com/33961674/125585915-fc75cea3-d902-4d0b-8d14-f027eca64052.png">

**Comment by fannheyward** [comment]
As my comment in https://github.com/fannheyward/coc-rust-analyzer/issues/763, how should the _client_ to improve this? LS, here is rust-analyzer, sends notifications and coc/coc-rust-analyzer displays them, if the client side hides them, you won't know what's wrong.

Maybe we can hide the `cargo check failed` error message from coc-rust-analyzer in *hard code*, but it's still not a good solution for this, because rust-analyzer abuses the notifications.

**Comment by GopherJ** [comment]
@fannheyward I think we can have a parameter to turn off notifications

**Comment by fannheyward** [comment]
This should be done in coc-rust-analyzer, not coc.

**Comment by chemzqm** [comment]
Use `"coc.preferences.enableMessageDialog": false`

**Comment by GopherJ** [comment]
@chemzqm I just tried to use `coc.preferences.enableMessageDialog: false` but it seems the notifications are still there:

![image](https://user-images.githubusercontent.com/33961674/130187706-41af8003-ed4a-4240-939a-3b7cee222e95.png)

**Comment by GopherJ** [comment]
Reproduce steps:

1. `:CocInstall coc-rust-analyzer`
2. `cd ~`
3. `cargo new hello-world`
4.  `vim ~/Cargo.toml` and put the following content
```
workspace.members = ["project-on-moon"]
```
5. vim `~/hello-world/src/main.rs`

**Comment by fannheyward** [comment]
@GopherJ why do you `vim ~/Cargo.toml` and `vim ~/hello-world/src/main.rs`? You didn't enter the `hello-world` root?

Can't reproduce in my tests:

1. `cd /tmp/`
2. `cargo new hello-world && cd hello-world`
3. `vim Cargo.toml` and add `workspace.members = ["project-on-moon"]` under `[dependencies]`
4. `vim src/main.rs`, no errors

**Comment by GopherJ** [comment]
@fannheyward I would assume `workspace.members` under dependencies doesn't make sense.

workspace Cargo.toml should contain child cargo project.

**Comment by chemzqm** [comment]
New notification works like VSCode, notifications with same options would be replaced.

**Comment by vimpostor** [comment]
Is it possible to disable progress notifications? `coc.preferences.enableMessageDialog` only has an effect on non-progress notifications.

**Comment by vimpostor** [comment]
@chemzqm I tried living with progress notifications to see if I start liking them after a week, but I still utterly despise them.

This is quite a bloated feature and I think there should be an upstream option to turn it off completely.
Also depending on the LSP used, it can be outright buggy, for example with the Texlab language server, I now have a permanent notification down there, because I start `texlab` with `-interaction=nonstopmode` to automatically build again when I write the file:
![Screenshot_20220610_233613](https://user-images.githubusercontent.com/21310755/173154403-90c2248e-67fc-46e7-b4bd-d00b3364972b.png)

This notification never disappears! But I didn't want to see that notification in the first place, there should be an option to disable **all** notifications.

**Comment by chemzqm** [comment]
You can add `progress` to `disabledFeatures` in your languageserver configuration.
Or use `:h coc-config-notification-disabledProgressSources`

**Comment by vimpostor** [comment]
> Or use `:h coc-config-notification-disabledProgressSources`

Thanks, `"notification.disabledProgressSources": ["*"],` in `:CocConfig` did the trick.
