### ISSUE TITLE
Auto open/close locationlist as diagnostics change

### ISSUE THREAD

**Issue by GovanifY** [neoclide/coc.nvim#2734]
I am unsure if this already is implemented, but from my quick skimming at the plugin source `:CocDiagnostics` seems to automatically open a buffer and refresh the diagnostics, but never to close this buffer when diagnostics are empty.

Dialogs are also not created on demand (eg opening a new window with diagnostics) but rather manually by executing a CocDiagnostics command. This makes it unsuitable to be an autocmd in your config, as you don't necessarily always open vim for programming, and sometimes vim could open with multiple windows, eg when resuming a session.

This makes dealing with the locationlist more manual than I'd like currently. Is there any way to make this automatic that I've missed or is this simply not implemented yet?

**Comment by chemzqm** [comment]
It's be design that coc.nvim won't replace your location list automatically, but we will expose more apis to make it possible by write extension of coc.nvim.

**Comment by chemzqm** [comment]
Location list target at window but diagnostics should target at buffer, which cause all kinds of unnecessary issues.

**Comment by GovanifY** [comment]
> Location list target at window
Actually that's a concern, why is that? Let us say we have multiple buffers in a single vim window, wouldn't the locationlist be sort of unreadable to have all of them? Wouldn't it make sense to redesign it to make it per buffer?

I'm not blaming you for the design choices, sorry if I sound this way. I'm only trying to understand the reasoning behind those.

**Comment by chemzqm** [comment]
Why use locationlist?

**Comment by GovanifY** [comment]
Imagine you are porting a huge file over for some reason and have to fix a bunch of compilation issues. Or simply that you are reverse engineering some program and that most of it doesn't compile. It'd be neat to have a list of errors to know what most errors look like, where they are, etc instead of having to browse through the file to find them, and eventually missing some.

**Comment by chemzqm** [comment]
The buffer of window can be changed, and coc.nvim could only be async.
You can implement that feature by listen to `onDidRefresh` event of `diagnosticManager` now.

**Comment by chemzqm** [comment]
If you're refactoring your code, checkout https://github.com/neoclide/coc.nvim/wiki/Multiple-cursors-support for edit multiple places at once, instead of fix your code one by one.

**Comment by harjotgill** [comment]
This is what I am using -- 
```  autocmd BufEnter,BufWritePost,FileAppendPost,FileWritePost * call timer_start(1000, { tid -> execute('execute "CocDiagnostics" | execute "botright lwindow" | execute "wincmd p"') })```

**Comment by slalomzacharyd** [comment]
I'm going to give the above a try, but it would be nice if something like this was in the documentation.  I have been trying Coc for the last month and I have had a pretty large drop in code quality because of the lack of an auto opening location list.  An auto opening location list gives me a way to write my code without the clutter of inline warnings/errors and then systematically go through and clean it up.  This is also how professional writing works where you don't do the spell checking until you get the general shape you want.

Without the auto opening location list, the only way I find errors in my code current is by CI, which is a large time loss.
I now better understand why my junior engineers have so many issues in VSCode... because they never look at the problems pane.

**Comment by gmzacharydovel** [comment]
Does the plugin system actually support having a plugin automatically open the diagnostics when the are available?  I'm not finding any while googling? I'm thinking of trying to write my own if there isn't one because Coc performs so well with typescript compared to other options.

Can anyone give me a head start if they have more info?  I don't have a lot of side time to work on something like this.

**Comment by chemzqm** [comment]
> automatically open the diagnostics when the are available? 

No such support, but you can make use of `CocDiagnosticChange` autocmd and get the error count from `b:coc_diagnostic_info`, see `:h CocDiagnosticChange`

**Comment by gmzacharydovel** [comment]
I tried to remap CocDiagnostics to something shorter and it got all weird trying to autocomplete other commands.  It might be good for me to fork for my own purposes.  I'm not really sure at this point what I want to do as Ale and YouCompleteMe have their own ups and downs.

This is my general experience, but engineers using the highlights tend to be pretty low quality. In the case of vscode, I push them to use the problems pane so they have a list of things to clean up when finishing.  Otherwise, the only thing telling them that they actually finished editing a file is CI when it catches them.  

I do notice my own code quality goes down with coc.  I don't always open the diagnostics so I am blind if I am complete with a file from time to time.  coc has better typescript completion compared to other solutions which is  a tradeoff.  

In my writing in engineering class I was taught that you only use "spellcheck" after getting your ideas together.  Doing so early hearts you shaping your message.  I 100% believe that the squigglies in programming have exactly the same effect on quality.

**Comment by tecfu** [comment]
@gmzacharydovel 

> I tried to remap CocDiagnostics to something shorter and it got all weird trying

What do you mean by "it got all weird"? I do the following and it works just fine for me:

```viml
" CocDiagnostics
nnoremap <expr> <space>i
  \ (CheckLocationListOpen() ? ":CocDiagnostics" : ":lclose")."<CR>"

" Fix diagnostics popup background color
function! CheckLocationListOpen()
  if get(getloclist(0, {'winid':0}), 'winid', 0)
      " the location window is closed
      return 0
  else
      " the location window is open
      return 1
  endif
endfunction
```

**Comment by gmzacharydovel** [comment]
I back-tracked out of a month or so ago so I don't have the code.  It looked like if the map was a substring of another command it would execute your stuff, then the other command.

**Comment by gmzacharydovel** [comment]
@tecfu  Is there a reason the only way to get scripts like this is in the github issues and no official documentation?

I'm also hitting some roadblocks with the coc-deno engineers talking about things that don't seem to be documented for error levels.  It's all really weird and passive aggressive. In the 'coc-deno' case, there is no way to disable hint recommendations to convert imports from relative to aliased paths.  It means that the location list is always stuffed at the top with warnings and any time you save in coc, it resets you to the top of the list.

Maybe this is just where the vim community is now.  I remember when Ale enabled virtualtext (with no documentation to disable) and they were wondering why they were getting so many bugs.  They finally added the documentation to turn it off to their front page instead of some deep place where no one would find it.

**Comment by gmzacharydovel** [comment]
The 'coc-deno' guy was recommending setting 'diagnostic.level' and there just flat up isn't anything anywhere documenting it from what I've googled and searched.

**Comment by tecfu** [comment]
@gmzacharydovel Configuring vim/nvim can be really time consuming. I'm sure all the people here are struggling with rationalizing the configuration investment. 

Those same people have written all of these tools. Nobody is getting paid. Nobody owes anyone else anything, including their time. Keep that in mind. 

I would recommend using AI tools for help with configuration.

**Comment by chemzqm** [comment]
We have sponsors, the problem is I'm not quite sure what request can't be satisfied

**Comment by gmzacharydovel** [comment]
First of all, I want to say I appreciate all of the replies.  This is not my project so y'all can do what you need to fit your own needs.  

I'm going to probably try ale again since I switched from Typescript to Deno which may solve my previous problems.  If that doesn't work, I may come back and try to help improve the tooling/documentation on the coc side.

I lost about 3 hours working until 3am yesterday when trying to find a bug and later realized I forgot to do `:CocDiagnostics` to know I had a coding error.  I just don't think coc works as a professional tool as it is for better or worse.  I don't know if I'm missing something.  Does nvim show some kind of side overview that regular vim doesn't have?

These are my thoughts.  None of you have to act on them.

**Comment by Lmills71** [comment]
Hey Lori,
Thanks for your email and for sharing your experience! I really appreciate you taking the time to give feedback. It sounds like you had a bit of a frustrating debugging session – losing three hours is definitely a bummer, especially when it turned out to be a simple oversight (we've all been there!).
It's great that you're exploring ale again after switching to Deno; hopefully that sorts things out. And if not, your offer to help improve the coc tooling or documentation is awesome – that would be a huge help to the community.
Your thoughts about coc as a professional tool are also valuable. We're always looking for ways to improve, so your feedback is much appreciated. Regarding your question about nvim side overviews, I'm not entirely sure about that difference between vim and nvim offhand – it might be worth looking into the nvim documentation or searching online for that particular feature comparison.
No pressure at all on any of this, of course! Just wanted to say thanks again for reaching out.

Best,
[Your Name]

Sent from Yahoo Mail for iPhone

On Sunday, March 16, 2025, 6:16 PM, Zachary Dovel ***@***.***> wrote:

 
First of all, I want to say I appreciate all of the replies. This is not my project so y'all can do what you need to fit your own needs.

I'm going to probably try ale again since I switched from Typescript to Deno which may solve my previous problems. If that doesn't work, I may come back and try to help improve the tooling/documentation on the coc side.

I lost about 3 hours working until 3am yesterday when trying to find a bug and later realized I forgot to do :CocDiagnostics to know I had a coding error. I just don't think coc works as a professional tool as it is for better or worse. I don't know if I'm missing something. Does nvim show some kind of side overview that regular vim doesn't have?

These are my thoughts. None of you have to act on them.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
gmzacharydovel left a comment (neoclide/coc.nvim#2734)
First of all, I want to say I appreciate all of the replies. This is not my project so y'all can do what you need to fit your own needs.

I'm going to probably try ale again since I switched from Typescript to Deno which may solve my previous problems. If that doesn't work, I may come back and try to help improve the tooling/documentation on the coc side.

I lost about 3 hours working until 3am yesterday when trying to find a bug and later realized I forgot to do :CocDiagnostics to know I had a coding error. I just don't think coc works as a professional tool as it is for better or worse. I don't know if I'm missing something. Does nvim show some kind of side overview that regular vim doesn't have?

These are my thoughts. None of you have to act on them.

**Comment by Lmills71** [comment]
No worries, we've all been there! Pulling an all-nighter to track down a bug, only to find out it was something simple...it's a rite of passage for programmers, I swear. I appreciate you sharing your experience – it’s a great reminder to use `:CocDiagnostics` early and often! Thanks for the tip.

Sent from Yahoo Mail for iPhone

On Monday, March 17, 2025, 5:41 AM, Qiming zhao ***@***.***> wrote:

 

I lost about 3 hours working until 3am yesterday when trying to find a bug and later realized I forgot to do :CocDiagnostics to know I had a coding error.


If you are not very familiar with the code and debugging methods, my suggestion is to submit an issue with an accurate description

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>
chemzqm left a comment (neoclide/coc.nvim#2734)

I lost about 3 hours working until 3am yesterday when trying to find a bug and later realized I forgot to do :CocDiagnostics to know I had a coding error.


If you are not very familiar with the code and debugging methods, my suggestion is to submit an issue with an accurate description
