### ISSUE TITLE
Error: E631: ch_sendraw(): write failed

### ISSUE THREAD

**Issue by luisdavim** [neoclide/coc.nvim#2750]
## Result from CocInfo

The command doesn't work, I get `Service stopped for some unknown reason, try :CocStart`
## Describe the bug

On start I see an error message:
```
Error on notify (VimEnter): Vim(cal):E631: ch_sendraw(): write failed
```

## Reproduce the bug

I was able to reproduce with the following file:

```
  set nocompatible
  set runtimepath^=~/.vim/bundle/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
```

**Comment by luisdavim** [comment]
this seems to be resolved in the latest tag

**Comment by teddy2021** [comment]
I have begun having a similar issue. 
It seems to have begun after getting You Complete Me, though I can't say if they're related. 
The message I'm getting is: 
`
Error detected while processing function <SNR>102_VimExitCallback[15]..<lambda>4[1]..<SNR>97_ExitCallback[41]..<lambda>5[1]..<SNR>99_StartWithCommand[13]..<SNR>99_StartLSP[31]..ale#lsp#StartProgram[27]..<SNR>108_SendInitMessage[67]..<SN
R>108_SendMessageData[2]..ale#job#SendRaw:
line    7:
E631: ch_sendraw(): write failed
`
It seems to always happen when I run vim after startup. The problem seems to go away when I restart vim.

**Comment by chemzqm** [comment]
@teddy2021 not seems issue with coc.nvim.
