### ISSUE TITLE
Ability to declare coc extensions to have installed.

### ISSUE THREAD

**Issue by jared-w** [neoclide/coc.nvim#282]
It would be great to have coc extensions setup through configuration rather than manual `:CocInstall my-extension` commands. I'm un-opinionated as to how this would be accomplished, but I do see a few potential solutions right off the bat:

* Minimal "wrapper" vim plugins for each extension (eg `Plug 'neoclide/coc-extension'` would suffice)
* A variable that can be set in the vimrc file, eg: `g:coc_extensions = [ 'json', 'rls', 'prettier', ...]`

Or however feels best. Ideally, I'd like to be able to clone my vim config, run `:PlugInstall`, then `:CocUpdate` and have everything I need without needing to remember or write down which extensions I have installed.

**Comment by docwhat** [comment]
@oblitum's code doesn't quite work.  If you swap out `!yarn install` with `cos#util#install()` then it really breaks things since CoC.nvim isn't done installing at that point and dies.

It would be really nice to have a global variable or (better yet) a `coc-settings.json` setting for configuring the desired plugins.

It wouldn't have to do anything special (like uninstall plugins or anything), just do what @oblitum's code does.

The only special check should be if someone uses `:CoCUninstall foobar` that it check if the install list contains `foobar` and if it does it should warn the user that next install/upgrade will re-install that extension.

**Comment by oblitum** [comment]
@docwhat, dunno what you mean by it not working since you change it? I use it as-is without issues.

**Comment by docwhat** [comment]
W00T! Thanks, @chemzqm.

...

Whups, I found a bug: #353 :cry:
