### ISSUE TITLE
bash-language-server 

### ISSUE THREAD

**Issue by esn89** [neoclide/coc.nvim#291]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
## versions
```
vim version: NVIM v0.3.1
node version: v8.9.0
coc.nvim version: 0.0.40
term: xterm-kitty
platform: darwin
```

## Error messages
```[coc.nvim] Server bash failed to start: Request initialize failed with message: EPERM: operation not permitted, scandir '/Users/esn89/Library/Calendars'```

## Output channel: languageserver.bash

**Describe the bug**
I've installed the bash-language-server via:  npm install -g bash-language-server
added this to my :CocConfig
	```	"bash": {
		      "command": "bash-language-server",
		      "filetypes": ["sh"],
		      "args": ["start"]
		}```
And I restarted nvim.  When I open nvim with a shell script, I see the above error.

**To Reproduce**
Steps to reproduce the behavior:
- npm install -g bash-language-server
- add the config for languageserver like above
- open a .sh file.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by oblitum** [comment]
With bash-language-server I recommend adding "~" to "ignoreRootPaths", it will scan your entire home if you open a bash script there.

**Comment by oblitum** [comment]
I'll add it as example on the Wiki.

**Comment by oblitum** [comment]
Updated: https://github.com/neoclide/coc.nvim/wiki/Language-servers#bash.

It may not be your issue though, but I recommend.

**Comment by esn89** [comment]
Ah I see.

Let me try it out.  Thanks!  

Btw why does this lang-serv need to scan my stuff anyways?

**Comment by oblitum** [comment]
@esn89 this happens to root resolve algorithm, check `g:rooter_patterns`, those are the default root markers coc use to define what's a root of a project to send to language server. The thing is it's quite common to open bash files in home, and it end up being resolved as a root project directory, this doesn't happen in general for other languages, because you're generally dealing with sources in their own git directory, with stops scanning for a parent directory for that, and they also have other root patterns, like `compile_commands.json`, that do the same.

**Comment by oblitum** [comment]
@esn89 please close the issue if that fixed it for you.

**Comment by chemzqm** [comment]
It's not issue of coc, the language server should be fixed to not index files in user's home.

**Comment by esn89** [comment]
Yes, it is fixed.  Thank you guys!
