### ISSUE TITLE
Lsp 3.16 PR merge

### ISSUE THREAD

**Issue by darzok0914** [neoclide/coc.nvim#3048]
Hi, first of all I just wanted to tell the creator, maintainers
And contributors a huge thanks for their awesome work. 

I saw the PR for lsp 3.16 and I was wondering if you had an idea of when (maybe a rough estimate ?) this will be merged?

**Comment by chemzqm** [comment]
When it's ready and I have time to review it.
Maybe after a month or so, I hope.

**Comment by darzok0914** [comment]
Thanks a lot for taking the time to respond:) what you're doing for the community is just incredible.

**Comment by fannheyward** [comment]
The https://github.com/neoclide/coc.nvim/pull/2756 thread is too long to comment, I'll update the LSP 3.16 status here.

1. API is ready, I mean the `language-client` part from `vscode-languageserver-node/client` is done, and tests passed
2. UI/UX part, for example tree view UI. I'd prefer to leave this for another PR, as @oblitum suggests
3. some API calls maybe not good enough, for example `willRename` file operation event will be fired in `workspace/renameCurrent`, https://github.com/neoclide/coc.nvim/issues/3050
4. semanticTokens highlights. How and when to define highlight group is better? LanguageClient-neovim uses [g:LanguageClient_semanticHighlightMaps](https://github.com/autozimu/LanguageClient-neovim/blob/a42594c9c320b1283e9b9058b85a8097d8325fed/doc/LanguageClient.txt#L516-L523).
5. semanticTokens needs nvim 0.5 to work
5. coc-json is broken, VSCode released https://www.npmjs.com/package/vscode-json-languageserver, this is only work with 3.16

I'm using the 316 branch in my daily work in the past months, include developing coc, coc 316 and coc extensions works. It's stable for tsserver, ESLint, gopls, rust-analyzer, Pyright and more.

**Comment by chemzqm** [comment]
> coc-json is broken

What does broken means? Current coc-json can't work with Lsp 3.16?

**Comment by fannheyward** [comment]
@chemzqm Yes. I have't find a way to make coc-json works with both 3.15 and 3.16.

**Comment by oblitum** [comment]
@fannheyward great work! I'm recently trying out nvim nightlies, initially just for this PR, but currently I'm migrating my conf to Lua. coc.nvim still just works fine. As coc tries to make things work out-of-the-box without much trouble for the user, I think it should provide an option for semantic highlight to working seamless:

> 4. semanticTokens highlights. How and when to define highlight group is better? LanguageClient-neovim uses g:LanguageClient_semanticHighlightMaps.

Currently, even though I'm using your PR, I have not yet benefited from it because I didn't yet setup any of the `CocSem_{tokenType}` highlighting groups. I think that besides the option of defining them manually (or ppl having to write coc-specific colorschemes), coc should provide an easier option for semantic highlight to work out-of-the-box.

I think that one solution to that is to have an option to associate `CocSem_{tokenType}`s to `TS{tokenType}`s automatically, because nvim 0.5 already have several [treesitter-focused colorschemes](https://github.com/RRethy/nvim-base16), and even though they're great, treesitter syntax matching isn't as powerful as lsp-semantic syntax matching, but [they may share a lot of related groups](https://github.com/RRethy/nvim-base16/blob/master/lua/base16-colorscheme.lua#L120-L153). I wonder whether this is possible and could be a flag to have it enabled/disabled.

**Comment by fannheyward** [comment]
@oblitum does `TS{tokenType}` came with nvim 0.5 or nvim-treesitter plugin?

**Comment by oblitum** [comment]
@fannheyward no idea sorry, nvim 0.5 is really new waters for me, I'd have to check it up what's what 😅.

**Comment by oblitum** [comment]
but at first, the colorscheme I linked doesn't seem to expect nvim-treesitter present, at least it's not mentioned in README, not sure whether that should be implied to have or not.

**Comment by fannheyward** [comment]
@oblitum looks like `TS{X}` are came from nvim-treesitter, and the colorscheme override them.

**Comment by fannheyward** [comment]
Another problem is neither `TS{X}` came from nvim or nvim-treesitter, they are only available in nvim, we need to make these work in vim.

**Comment by oblitum** [comment]
@fannheyward lsp highlight is supposed to work on vim too then? I didn't thought of that.

**Comment by fannheyward** [comment]
@oblitum define hi group and use it, I think it's possible.

**Comment by g-suraj** [comment]
Any updates on when this feature can land? :)

**Comment by chemzqm** [comment]
Merged to master, feedback welcome.
