### ISSUE TITLE
[coc.nvim] build/index.js not found, please install dependencies and compile coc.nvim by: yarn install

### ISSUE THREAD

**Issue by Exocrean** [neoclide/coc.nvim#3308]
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
Use `release` branch.

**Comment by sigmaSd** [comment]
I think this can be handled better by coc

The problem is if you don't have yarn installed *before* installing coc the error becomes unclear, and you have to search the issues to find the above comment with the solution.

In contrast for example coc will not install if `node` is not present, I think it would be better if it acted the same with `yarn`
