### ISSUE TITLE
[bug] A bug about <plug>(coc-codeaction-selected)

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc.nvim#3407]
Reproduce procedures and environment information see <https://github.com/fannheyward/coc-pyright/issues/632>.

Thanks!

**Comment by fannheyward** [comment]
With your configuration and sample code:

```py
def init() -> None:
```

when you do `g.$`, coc.nvim will call `getpos`:

1. `getpos("'[")`, got start line and start character, `1 1`
2. `getpos("']")`, got end line and end character, `1 19`
3. get position from line number and col number, `{ line: 0, character: 0 }` and `{ line: 0, character: 18 }` because LSP counts from zero
4. the range, `{ start: { line: 0, character: 0 }, end: { line: 0, character: 18 } }`, doesn't include `:`, this caused the problem
