### ISSUE TITLE
Option to disable a server if the root pattern is not found

### ISSUE THREAD

**Issue by reaysawa** [neoclide/coc.nvim#344]
**Describe the bug**
I use the Flow LSP with my Javascript files, but the server fails to start if a `.flowconfig` file is not found in the current working directory. It creates a problem where the server will start and crash if I'm editing a Javascript file in another project, without flow.

**To Reproduce**

1. Start a server that requires a specific configuration file (e.g. Flow needs `.flowconfig`)
2. Open a file in another project that does not have `.flowconfig`
3. The server will crash because the file isn't found

**Suggestion**
Have an option to disable the server if the root pattern is not found.

**Comment by reaysawa** [comment]
hi @chemzqm I have updated to the latest master but it seems like this was not resolved, still getting the same error @_@

```
  "languageserver": {
    "flow": {
      "command": "flow",
      "args": ["lsp"],
      "filetypes": ["javascript", "javascript.jsx"],
      "initializationOptions": {},
      "requireRootPattern": true,
      "settings": {},
      "rootPatterns": [".flowconfig"]
    }
  },
```

**Comment by chemzqm** [comment]
You should not `tag:*` in `Plug` command if you want to use master code.

**Comment by tomspeak** [comment]
@chemzqm if you are building from master and have this configuration:

```
{
  "tsserver.enableJavascript": false,
  "languageserver": {
    "flow": {
      "command": "flow",
      "args": ["lsp"],
      "filetypes": ["javascript", "javascriptreact", "javascript.jsx"],
      "initializationOptions": {},
      "requireRootPattern": true,
      "settings": {},
      "rootPatterns": [".flowconfig"]
    }
  }
}
```

Do you know why I get the error:

`[coc.nvim] Command "flow" of LS "flow" not found in $PATH` - from a directory without `.flowconfig`?

**Comment by chemzqm** [comment]
It's detected on coc initialize

**Comment by tomspeak** [comment]
@chemzqm -- ah, I thought that `requireRootPattern` would cancel `flow` being loaded when a `.flowconfig` file was not present? I may have misunderstood.

**Comment by chemzqm** [comment]
Add flow to your $PATH or use absolute command path

**Comment by siddharth99** [comment]
I am facing a similar issue; any help or workaround would be great. My coc-config file is as listed below; the code directory consists of multiple nested git repositories.

```
{
  "timeout": 1000,
  "hoverTarget": "echo",
  "rootPatterns": [".ccls-root"],
  "languageserver": {
    "ccls": {
      "command": "ccls",
      "args": ["--log-file=/tmp/ccls_coc.log"],
      "trace.server": "verbose",
      "filetypes": ["c", "cpp", "objc", "objcpp"],
      "rootPatterns": [".ccls-root"],
      "initializationOptions": {
        "cacheDirectory": "/tmp/ccls_coc",
        "compilationDatabaseDirectory": "/home/code",
        "index": {"threads": 4},
        "clang": {"resourceDir": "/x/clang60/lib/clang/6.0.1"},
        "completion": {"filterAndSort": true}
      }
    }
  }
}
```
I created a file /home/code/.ccls-root
If I open a file /home/code/repo1/folder1/main.cpp the workspace directory in ccls log is set as /home/code/repo1 (which contains a .git file but I removed .git from rootPatterns).

I tried setting rootPatterns to compile_commands.json, .ccls-root (touch .ccls-root) but none of them are able to set the workspace-directory in ccls correctly. I am just dealing with 1 large code-base so don't really indend to use multiple workspaces for now.

Just to confirm the problem the async linting is working file but none of the goto definition, implementation type things are working.

LanguageClient-neovim doesn't have support for workspace directories (afaik) and it was able to find the LC root directory correctly probably just using compile_commands.json since I didn't have to specify anything on it. Here, I also need to specify compile_commands.json manually; I would very much like to switch to coc.nvim since it works better than languageclient-neovim which seems to get stuck ever so often for me.
