### ISSUE TITLE
No cursor in CocList

### ISSUE THREAD

**Issue by rickboks** [neoclide/coc.nvim#3466]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.1
node version: v16.11.1
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /home/rick/.local/share/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2021-11-11T16:15:19.948 INFO (pid:128025) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v16.11.1 after 139ms
2021-11-11T16:15:22.514 INFO (pid:128025) [attach] - receive notification: showInfo []
```

## Describe the bug

When using CocList interactively (with any source), there is no visible cursor. See the GIF below.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Run `:CocList commands`
## Screenshots (optional)
![Peek 2021-11-11 16-13](https://user-images.githubusercontent.com/27772913/141322845-d18e0133-1623-40bb-8526-d902dc218793.gif)

**Comment by oblitum** [comment]
`:h g:coc_disable_transparent_cursor` may help you.

I can't reproduce the problem myself.

**Comment by rickboks** [comment]
Thank you. setting `let g:coc_disable_transparent_cursor = 1` results in the following. Note that the cursor stays in the bottom left.
![Peek 2021-11-11 16-55](https://user-images.githubusercontent.com/27772913/141328488-65e75765-6906-4515-8446-c47471562d27.gif)

**Comment by oblitum** [comment]
Ah okay. Well, so cursor transparency is actually working for you. That cursor stuck there is the real cursor, but as you can notice the display isn't nice, so coc makes it transparent by default. The other one that should have been displayed and is put where you type is actually a fake cursor that coc implements for CocLis (if I recall correctly). So, tl;dr, on CocList implementation in general you have the real cursor set to transparent, and the fake on being shown, otherwise you would see two cursors. I have no idea why the fake one isn't being shown for you.

**Comment by oblitum** [comment]
Hmm, the fake cursor should be implemented through [this](https://github.com/neoclide/coc.nvim/blob/19a630de325ed71e153e8ca89f114b040c878b1b/src/list/prompt.ts#L83), which highlights a space character with the `Cursor` highlight group. Your `Cursor` highlight group should be the issue, try `:hi Cursor`, and try changing it. It shouldn't be an issue in most colorschemes.

**Comment by rickboks** [comment]
Yes! Setting `hi Cursor ctermbg=white ctermfg=white` solved the problem. Many thanks for the help @oblitum. This had been bugging me for a while :)
