### ISSUE TITLE
[coc.nvim] implementation not found (C++)

### ISSUE THREAD

**Issue by T0maas** [neoclide/coc.nvim#3490]
# Problem
I have issue with finding implementation in c++ code.  It can not  find implementation in different file in same folder.

I have this code:
main.cc
```
#include "test.h"
int main() {
    Testme();
    return  0;
}
```
test.h:
```
#pragma once
extern void Testme();
```
test.cc
```
#include "test.h"
#include <cstdio>
void Testme() {
    puts("test");
}
```
.ccls
```
g++
-I.
```
All files are in same folder. `coc-definition` and `coc-references` works as expected but `coc-implementation` shows _[coc.nvim] implementation not found_, when I put cursor to Testme() in main.cc and press `gi` (which is set as `nmap <silent> gi <Plug>(coc-implementation)`). 

My coc-settings.json contain this:
```
{
    "diagnostic.refreshOnInsertMode": true,
    "languageserver":{
        "ccls": {
            "command": "ccls",
            "filetypes": ["c","cc" ,"cpp", "objc", "objcpp"],
            "trace.server": "verbose",
            "initializationOptions": {
                "cacheDirectory": ".ccls-cache"
            }
        }
    }
}
```
# Expected result
`coc-implementation` should find implementation in `test.cc`

___
PS: `coc-definition`  shows definition (in test.h) and also implementaion (int test.cc)

**Comment by oblitum** [comment]
This is a language server implementation problem (`ccls`), not coc one. With coc-clangd, if you have both `.cc` files open, it works:

`coc-declaration` in `main.cc` -> goes to `Testme()` in `test.h`
`coc-definition` in `main.cc` -> goes to `Testme()` in `test.cc`
`coc-implementation` in `main.cc` -> implementation actually isn't used in c++ context, just "declaration" and "definition"

In general in c++, cross file go-to-def isn't much supported by language servers because it's a kind of file scan problem, not language problem, and language servers don't in general implement a feature of seeking and matching all your files to figure out the most probable definition of a given function prototype, when they do, they in general expect some specific file pattern names. That's why it's best in general to rely on ctags for this.
