### ISSUE TITLE
Add CocClean command

### ISSUE THREAD

**Issue by hodapp512** [neoclide/coc.nvim#3908]
g:coc_global_extensions variable items are sometimes removed in which instance those plugins are not removed. The simplest way to remove them is to run :CocUninstall on each of them.

It would be simpler to have :CocClean command which removes any installed language plugin not in the g:coc_global_extensions variable.

Related: https://github.com/neoclide/coc.nvim/issues/2857

**Comment by fannheyward** [comment]
No, not everybody use `g:coc_global_extensions` to install extensions, if `CocClean` to remove any installed extensions that not in `g:coc_global_extensions`, people got unexpected effects.

You can `:CocList extensions` to list all extensions, `tab` on any extension and `u` to uninstall it.

**Comment by Magicrafter13** [comment]
I've seen several issues on this repo asking for the same thing and your response always seems to be the same.

I understand not wanting to automatically do something like this (since, if that behavior is unexpected, people are going to be like "where the hell did my plugin go?"), but surely you can add a *separate* command whose purpose is uninstalling extensions not listed in the global variable.

And if not, is there at least some easy way to get a list of the installed extensions that doesn't require user input? I manage my neovim config with a script. And in my script I update and clean all my regular plugins easily by just sending the proper vim-plug commands. Up until this point however, my solution to having coc extensions I don't want is to just remove all of them and trigger a reinstall, which is not optimal. I just need some script friendly way of doing this, and running a command that lists *all* where I have to push `tab` a variable number of times, does not fit that description.

**Comment by fannheyward** [comment]
> get a list of the installed extensions that doesn't require user input

`:echo CocAction('loadedExtensions')`

**Comment by chemzqm** [comment]
We don't provide that kind of command because it's common to use a different vimrc, that may cause extensions unexpected removed, you can create the command by use API from coc.nvim.

**Comment by Gee19** [comment]
Stumbled upon this issue randomly and decided to play around with some vimscript, this is what I came up with:

```
" Remove plugins not explicitly defined in g:coc_global_extensions
" Ignore special case: friendly-snippets
function! CocClean() abort
  let g:extensions_to_clean = CocAction("loadedExtensions")
      \ ->filter({idx, extension -> extension !~ 'friendly-snippets'})
      \ ->filter({idx, extension -> index(g:coc_global_extensions, extension) == -1})
  if len(g:extensions_to_clean)
    exe 'CocUninstall' join(map(g:extensions_to_clean, {_, line -> split(line)[0]}))
  else
    echo 'Nothing to clean'
  endif
endfunction
command! -nargs=0 CocClean :call CocClean()
```
