### ISSUE TITLE
Add snippet indicator after completion item resolved

### ISSUE THREAD

**Issue by mainej** [neoclide/coc.nvim#3911]
**Is your feature request related to a problem? Please describe.**
If a language server provides `additionalTextEdits` for a completion item during `textDocument/completion`, the completion item gets a "snippet indicator" in the completion results menu. But if the server provides `addtionalTextEdits` during `completionItem/resolve`, the snippet indicator isn't added to the completion item. This is frustrating because it's not possible to know which completion items will edit other parts of the document. For example, it can be useful to have an indication that choosing a completion item might unexpectedly "import" a module that hasn't been imported before.

**Describe the solution you'd like**
When a completion item is resolved with additional text edits it should get a snippet indicator.

**Describe alternatives you've considered**
I'm not aware of any workarounds.

**Additional context**

Expected (notice 🍦)

<img width="360" alt="Screen Shot 2022-07-04 at 10 52 49 AM" src="https://user-images.githubusercontent.com/6774/177200962-8f7e89bf-6649-456e-866b-7152441d4f72.png">

Actual

<img width="351" alt="Screen Shot 2022-07-04 at 10 53 05 AM" src="https://user-images.githubusercontent.com/6774/177200964-51ddb502-4041-4ee8-b7f0-23bbca6eba63.png">

**Comment by mainej** [comment]
@fannheyward [these lines](https://github.com/neoclide/coc.nvim/blob/3ad5f86b9d31d548e7ed8b178d279f54d122ebf4/src/sources/source-language.ts#L210-L211) are what makes `additionalTextEdits` behave like snippets. The bug is, I think, that those lines are called during `doComplete`, but not during `onCompleteResolve`, which means that if the server adds `additionalTextEdits` as it's resolving the completion item (which coc.nvim has [asked it to do](https://github.com/neoclide/coc.nvim/blob/cc41df829dd2c2ad3f6fff095d9f18a746e84b86/src/language-client/client.ts#L1881)) then the completion item won't get the snippet indicator.

**Comment by fannheyward** [comment]
@mainej Got your point, will look into this.

**Comment by snoe** [comment]
It's really nice to have the indicator for `additionalTextEdits` since those edits can be far from the cursor. I hope this can be consistent between  `doComplete`, and `onCompleteResolve`.

In clojure, for instance, large project often end up with similarly aliased namespace references. The snippet helps me pay attention to the origin of the completion so that I pick the right one (often choosing completions that have already been used locally, thus easily choosing the ones without an indicator). Getting the correct `log` namespace is easy with the indicator; without it I would have to look at each one carefully. 

<img width="273" alt="image" src="https://user-images.githubusercontent.com/105012/180819528-f7939610-aa1f-45a0-b01e-cbccfb2f22ad.png">

**Comment by chemzqm** [comment]
Not possible to update to pum, you have  to check the documentation window (if exists).
