### ISSUE TITLE
changed highlight group for new autocomplete menu?

### ISSUE THREAD

**Issue by liamtimms** [neoclide/coc.nvim#3980]
## versions

vim version: NVIM v0.7.2
node version: v16.16.0
coc.nvim version: 0.0.82-ebe19461 2022-08-02 04:07:00 +0800
coc.nvim directory: /home/liam/.config/nvim/plugged/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2022-08-01T19:03:01.808 INFO (pid:148086) [plugin] - coc.nvim initialized with node: v16.16.0 after 186ms
2022-08-01T19:03:04.233 INFO (pid:148086) [attach] - receive notification: showInfo []

## Describe the bug

While scrolling between completion options, the menu does not highlight the currently selected choice once a color scheme is applied.  

However, it highlights in pink as expected with default nvim colors. My guess is a highlight group has changed which themes will need to add or adjust for. 

## Reproduce the bug

Apply a theme (tested with 'marko-cerovac/material.nvim' and 'Mofiqul/dracula.nvim'), then attempt to use autocomplete with the suggested configuration settings from README. 

## Screenshots 

screencast where I am scrolling through options, built in ctrl+n works as expected but coc completions do not:

[Screencast from 08-01-2022 07:58:41 PM.webm](https://user-images.githubusercontent.com/14281621/182264490-46557869-6a96-4825-b313-332b88a29a17.webm)

[Screencast from 08-01-2022 08:02:07 PM.webm](https://user-images.githubusercontent.com/14281621/182264750-329ad487-9685-494e-b8f1-6cd9844c301b.webm)

**Comment by liamtimms** [comment]
adding a highlight color for CocMenuSel seems to work as a workaround: https://github.com/liamtimms/dracula.nvim/commit/90ba2b5e6b1b62024cb75383b955aa362c3edf63

[Screencast from 08-01-2022 09:14:07 PM.webm](https://user-images.githubusercontent.com/14281621/182271052-53553243-2769-4611-bd64-4cda3e878dcd.webm)

however, it's unclear if breaking previously working theming was intentional.

**Comment by fannheyward** [comment]
I'm using `dracula/vim` and `CocMenuSel` works as expected.

**Comment by oblitum** [comment]
On my side this broke too (I use zenbones). `CocMenuSel` is presented simply as `cleared` in `:verbose hi CocMenuSel`.

**Comment by oblitum** [comment]
Just a shot in the complete dark here. I see vim vs nvim colorschemes here, which may hint at something nvim specific. Last time I saw this happening related to colorschemes was here, and it was very weird nvim bug:

- https://github.com/mcchrish/zenbones.nvim/issues/86

**Comment by fannheyward** [comment]
@oblitum your `:verbose hi CocMenuSel` output `cleared`?

**Comment by oblitum** [comment]
@fannheyward yep.

**Comment by chemzqm** [comment]
You could be using autocmd to change colorscheme, you have to make the autocmd nested to fire ColorScheme event `:h autocmd-nested`

**Comment by alextes** [comment]
I just ran into this. The default CocMenuSel turns into a strong cyan for me.

![Screenshot 2022-08-02 at 14 25 59](https://user-images.githubusercontent.com/2011351/182374095-e0883cdb-b782-4103-a138-4fece5ab1371.png)

Here's something that might work better for most color schemes:
```
highlight CocMenuSel ctermbg=19 guibg=#222222
```
![Screenshot 2022-08-02 at 14 25 36](https://user-images.githubusercontent.com/2011351/182374289-857d6cf2-60c6-4a45-aee5-99e39ad71a40.png)

Thanks for pointing out the highlight group to look for! This should be pretty easy to reproduce for many color schemes if the default stays colored instead of something like a gray that works with many color schemes.

Thanks for a great plugin!

**Comment by chemzqm** [comment]
@liamtimms I can't reproduce, try minimal vimrc.

**Comment by alextes** [comment]
@chemzqm my bad! I totally read this wrong. This should be "can't reproduce" if you can't reproduce the scrolling issue. My issue might be related, people not seeing the CocMenuSel highlight because it is simply the same as the default highlight of the completion menu but it doesn't have to be actually.

Anyway, if others don't see the highlight, try changing the color of the group. Maybe it's that. Seems "can't reproduce" is fair! Sorry!

**Comment by oblitum** [comment]
> The highlight groups could be cleared.
> You could be using autocmd to change colorscheme, you have to make the autocmd nested to fire ColorScheme event `:h autocmd-nested`

Thanks @chemzqm, this seems relevant. I am reproducing this issue, like many others are, and this seems potentially due to that. The fact is, I'm using packer as plugin manager, and my colorscheme is set inside a packer `config` setup function, the way this eventually gets invoked may be something akin to an `autocmd` in the end, but without `nested`, and I think I can't change that.

Executing the command `:colorscheme rosebones` manually (meaning, not from an `autocmd`), the issue is gone. I now have to check where should I place `coloscheme` command on my init to avoid this issue.

**Comment by chemzqm** [comment]
> I totally read this wrong. This should be "can't reproduce" if you can't reproduce the scrolling issue. My issue might be related, people not seeing the CocMenuSel highlight because it is simply the same as the default highlight of the completion menu but it doesn't have to be actually.

Default color of CocMenuSel changed to a light blue background like VSCode, in case some colorscheme set CursorLine the same as Pmenu (linked to CocFloating by default)

**Comment by oblitum** [comment]
> I now have to check where should I place `coloscheme` command on my `init.lua` to avoid this issue (which I have no idea, any place seems not to work).

Just put this as final line of my `init.lua`, didn't work. I'm out of ideas now as to why it works from command, but not from init.

```lua
vim.cmd [[
    autocmd init VimEnter * ++nested colorscheme rosebones
]]
```

**Comment by oblitum** [comment]
Current selection highlight has got fixed from my side lately, but not the behavior of sign colors, but I was able to get that fixed in packer.nvim by sequencing plugin loading order. I added `after = 'zenbones.nvim'` (which is my colorscheme set of choice) to the `coc.nvim` plugin entry, so that it loads only after zenbones is finished, and this made colors work as-if by `:colorscheme xyzbones` command.
