### ISSUE TITLE
Can you delete coc#ui#check_pum_keymappings or let users configure to disable it?

### ISSUE THREAD

**Issue by suewonjp** [neoclide/coc.nvim#4530]
Thank you for the great tool! coc.nvim makes my life easier 👍 

**Is your feature request related to a problem? Please describe.**
In function [coc#ui#check_pum_keymappings](https://github.com/neoclide/coc.nvim/blob/79e9e048dfedbfc8b91330059fec5470f8b68f14/autoload/coc/ui.vim#L9-L25), you overwrite Vim's `pumvisible` builtin function. This causes some trouble to some users (like me) using that builtin to customize their own mappings.  (e.g. I use `<tab>` for dictionary completion. As a detail, I use `<leader><tab>` to start dictionary completion, and after it started, I use simply `<tab>` to reach a desired word for which I have to use `pumvisible` builtin. `coc#pum#visible` doesn't seem to work with dictionary completion.)

I guess you added that `coc#ui#check_pum_keymappings` for users using old .vimrc configurations. 
I think your [old .vimrc configuration example at README](https://github.com/neoclide/coc.nvim/tree/v0.0.63#example-vim-configuration) file used to use `pumvisible`, but now you're using `coc#pum#visible` for the example so overwrite like this might be unnecessary any more, I guess...

**Describe the solution you'd like**
Simply deleting `coc#ui#check_pum_keymappings` if you think it's not necessary any more

**Describe alternatives you've considered**
Or providing some configuration switch that users can disable it if you think deleting it might be risky yet.

**Comment by suewonjp** [comment]
Currently, I simply comment out `coc#ui#check_pum_keymappings` function every time I update coc.nvim...

**Comment by fannheyward** [comment]
Yes, we use `coc#ui#check_pum_keymappings` to check and remap tab/cr etc. Maybe we can remove this checking in next tag release, or add a configuration to disable this checking.

**Comment by mmrwoods** [comment]
Please bear in mind that other folks might now be expecting this behaviour so changing it will break their configs. I'm not saying that's a a good enough reason not to do it, but it might be best to make this something people can opt out of, rather than just delete it, or at least retain it as something people can opt in to.

FWIW I have completion aware `<Tab>`, `<S-Tab>` and `<CR>` mappings in my vimrc, but I also use coc.nvim occasionally, enabling it as needed.  As things stand these mappings magically just work with coc.nvim when I enable it. I'm probably not alone here.
