### ISSUE TITLE
More information about LSP related plugins

### ISSUE THREAD

**Issue by zgpio** [neoclide/coc.nvim#454]
**Description**
  I am a new user. I want to know more about the `coc` plugin. 
Can you introduce the similarities and differences between the [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) and `coc.nvim` in terms of features, user interfaces, implementations, etc?
I think the relevant plugin information can also be presented in the readme. Of course, this is just a personal point of view.

**Comment by chemzqm** [comment]
Checkout https://github.com/MaskRay/ccls/wiki/Editor-Configuration for exmaple.

Supported language server features: https://github.com/neoclide/coc.nvim/wiki/Language-servers#supported-features.

Coc have full LSP completion feature support, builtin list support, and works with VSCode like extensions (so we don't have to use broken language server like: https://github.com/sourcegraph/javascript-typescript-langserver)

**Comment by chemzqm** [comment]
I've been not using LanguageClient-neovim for sometime, so correct me if there's somethine wrong below.

* Coc have buildin completion support, LanguageClient-neovim requries other completion engine for auto trigger completion.
* You can choose other completion engine for LanguageClient-neovim, but you can't do it when using coc.nvim.
* Binary release of coc is much bigger than LanguageClient-neovim, because it's build with pkg which contains node runtime.
* LanguageClient-neovim can provide rename buffer for rename operation, which is not complemented in coc yet.
* Coc support VSCode like extensions, which could be more powerful and easy to use, most importantly, you don't have to use broken language server like: https://github.com/sourcegraph/javascript-typescript-langserver
* Coc support VSCode like configuration files, makes it more flexiable.
* Coc have builtin list support and provide list sources for work with coc: https://github.com/neoclide/coc.nvim/wiki/Using-coc-list
* Coc support multiple language server for same buffer, and most LSP features support multiple language servesr work at same time, seems LanguageClient-neovim doesn't have that support yet.
* Coc have support for LSP completion support, default omni completion provided by LanguageClient-neovim only have some basic suppport.
* Coc have full support for LSP features, except for workspaceFolders,  LanguageClient-neovim support some of them.
* Coc support buffer sync event of neovim, which improves performance for editing large files, while LanguageClient-neovim have to synchronize full buffer content on every change.
* Coc support increment buffer change event of LSP, LanguageClient-neovim only support full document synchronize.
* Coc have many useful extensions.
* Coc support debug language server use output channel: https://github.com/neoclide/coc.nvim/wiki/Using-coc-list,  LanguageClient-neovim could be not supporting it.
* Coc is written in typed language and tested on CI

**Comment by dpriedel** [comment]
I've used vim for many years and I have used YouCompleteMe for a few years and have tried all the other major autocomplete plugins for vim.  By far, Coc is the best autocomplete solution I have used. I currently also use ALE for running Clangtidy and really appreciate that Coc can use ALE to show diagnositcs. 

Would it be possible to have some more sample configurations particularly for multiple LSPs for a buffer. I primarily do C++ development and use CCLS for my LSP with Coc. 

Thanks for the great tool !!

**Comment by chemzqm** [comment]
> Would it be possible to have some more sample configurations particularly for multiple LSPs for a buffer.

There's no special configuration needed for multiple LSPs work together, they just works.
It mostly useful fo coc extensions that contribute specific feature, like:
https://github.com/neoclide/coc-highlight
https://github.com/neoclide/coc-emmet
https://github.com/neoclide/coc-prettier
https://github.com/neoclide/coc-eslint
