### ISSUE TITLE
workspace.rootPatterns is not actually honored

### ISSUE THREAD

**Issue by untitaker** [neoclide/coc.nvim#4587]
It seems to me that workspace.rootPatterns is not actually supported on master?

0. install coc-rust-analyzer
1. configure a setting like this: `"workspace.rootFolders": ["Cargo.toml"]`
2. check out https://github.com/getsentry/snuba
3. `cd rust_snuba/`
4. `CocCommand workspace.workspaceFolders` is still pointing to the git root, not the inner folder

this does work, however:
```
autocmd FileType rust let b:coc_root_patterns = ['.git', '.venv', 'Cargo.toml']
```

**Comment by fannheyward** [comment]
1. you don't need to config `workspace.rootFolders` because coc-rust-analyzer already provides this
2. after your step 3, do you open any rust file? `CocCommand workspace.workspaceFolders` is empty without open any files.


My tests:

1. `cd rust_snuba`
2. `vim src/config.rs`
3. rust-analyzer works as expected, `CocCommand workspace.workspaceFolders` is `xxx/snuba/rust_snuba`

**Comment by untitaker** [comment]
the exact test you are doing results in `workspaceFolders = xxx/snuba` for me. feel free to close if this is not reproducible, i have an adequate workaround and i suppose this is something weird about my environment not worth debugging

**Comment by untitaker** [comment]
> you don't need to config workspace.rootFolders because coc-rust-analyzer already provides this

to be clear, no that's not what's happening for me. I am not sure why.
