### ISSUE TITLE
:call CocAction('jumpReferences', 'vsplit') doesn't work

### ISSUE THREAD

**Issue by ssh352** [neoclide/coc.nvim#4671]
both
nmap <silent> gr :call CocAction('jumpReferences', 'vsplit')<CR>

and
nmap <silent> gr :call CocAction('jumpReferences', 'tabe')<CR>

could anyone advise how to make it work? Thanks

**Comment by ssh352** [comment]
I really want the references show up in vertical split or new tab because the monitor is flat and horizontal split is too short.

**Comment by fannheyward** [comment]
1. you need to add `<CR>` to your mapping end
2. if there's only one reference result, `CocAction('jumpReferences', 'tabe')` will open it directly, otherwise, references will be displayed in list view.
3. try `nmap gr :call CocAction('jumpUsed', 'tabe')<CR>`, this will jump to references exclude declarations.

What you most want to resolve is all results listed in a horizontal split, it's hard to view. Try https://github.com/kevinhwang91/nvim-bqf, this can display the results in quickfix and preview in floating window.

**Comment by ssh352** [comment]
> 1. you need to add `<CR>` to your mapping end
yes I have it 

> 2. if there's only one reference result, `CocAction('jumpReferences', 'tabe')` will open it directly, otherwise, references will be displayed in list view.
oh, it has multiple references instead of one,  how could I have the list view for references be in a vertical split?

> 3. try `nmap gr :call CocAction('jumpUsed', 'tabe')<CR>`, this will jump to references exclude declarations.
If it finds multiple references, it still shows in a horizontal split, not open in a new tab. 

> 
> What you most want to resolve is all results listed in a horizontal split, it's hard to view. Try https://github.com/kevinhwang91/nvim-bqf, this can display the results in quickfix and preview in floating window.

Thanks, Currently the list view looks like this, I'd really like the context to be taller. That's why I thought making it a vertical split is a good idea. @fannheyward 

<img width="899" alt="Screenshot 2023-06-09 at 11 01 50" src="https://github.com/neoclide/coc.nvim/assets/41779116/60332acc-0635-4e47-a549-61e7b15eb660">

**Comment by fannheyward** [comment]
CocList only supports horizontal split by now.
