### ISSUE TITLE
Support multiple formatters by chaining them

### ISSUE THREAD

**Issue by achimnol** [neoclide/coc.nvim#4726]
It was mentioned that CoC supports only a single formatter in #2269 more than 3 years ago.
After about one year, Neovim got synchronous serial execution of formatters (neovim/neovim#14371, neovim/neovim#14462).

Could we have the same mechanism in CoC as well?

Usecase: Apply Ruff autofix followed by Black formatter (or vice versa) in Python codes.

**Comment by achimnol** [comment]
My current workaround is to use an `.exrc`:
```vim
function! OrganizeAndFormat()
    CocCommand ruff.executeOrganizeImports
    sleep 50m
    call CocAction('format')
    sleep 50m
endfunction

augroup autofix
    autocmd!
    autocmd BufWritePre *.py if &modified | call OrganizeAndFormat() | endif
augroup END
```
But I'd like to implement this without worrying about race conditions, etc.

**Comment by fannheyward** [comment]
I'm a little doubt nvim's multiple formatting:

https://github.com/neovim/neovim/blob/8861f2af72481b1759a6935afa6dce2aae512359/runtime/lua/vim/lsp/buf.lua#L244-L251

nvim loops attached clients, `request_sync` formatting method, with _document uri_, applies result (by `nvim_buf_set_text`).

Does nvim save the document at this point? If not, the second formatter runs with the _unchanged_ document because LS only use uri as parameter, is the second formatting-task working properly?

**Comment by achimnol** [comment]
I don't have the inner details on how neovim works, but just my search through GitHub revealed that they have considered multi-formatter issues a while ago. I'm not sure how they work today beacuse I've failed to migrate my CoC-based configurations to neovim's native LSP configurations and related plugins.

It would be still great if I could enforce some kind of synchronization between subsequent buffer updates in my custom `BufWritePre` autocmd, even the intrinsic multi-formatter support is not added to CoC.

**Comment by chemzqm** [comment]
The problem is `CocCommand` send notification to node process, but you have to use request here, use `:call CocAction('runCommand', 'ruff.executeOrganizeImports')` instead, no need to use `sleep`
