### ISSUE TITLE
No intellisense from tsserver for .tsx files

### ISSUE THREAD

**Issue by city41** [neoclide/coc.nvim#48]
**Describe the bug**
The typescript language server works for `.ts` files, but not `.tsx`

**To Reproduce**
1. Open a typescript project that has .tsx files
2. Open a tsx file
3. attempt to use intellisense such as getting the properties from a type

```
type MyType = { bar: string };
function foo(a: MyType) {
    return a.b    <----- expecting autocomplete of "bar" here
}
```

**Expected behavior**
Expecting the intellisense to autocomplete based on the type using the ts language server

Actual behavior: the intellisense is just based on other sources such as `around`
**Screenshots**

![screenshot](https://i.imgur.com/Uo4y3vm.png)

**Desktop (please complete the following information):**
 - Terminal: mintty on Windows 10 (ssh'd into Ubuntu 16.04 machine)
 - Version: nvim v0.3.2-188-g821310930

**Additional context**
Everything works as expected in `.ts` files. A tsx file has filetype of `typescriptreact`. When I do `set filetype=typescript`, I see two messages from coc.nvim indicating it found tsserver and is using it. But despite that, I still don't get the expected behavior in tsx files.

Here is my init.vim: https://github.com/city41/dotfiles/blob/master/config/.config/nvim/init.vim

Thanks for this great plugin!

**Comment by city41** [comment]
Works great! Thanks for the quick fix!

**Comment by QuadeMorrison** [comment]
This commit seems to have broken the plugin when using the typescript.jsx filetype, which makes sense since you replaced typescript.jsx with typescriptreact. I'm interested in how a tsx file got set to the filetype typescriptreact because vanilla nvim doesn't even recognize typescript files out of the box as of version 0.3.1, meaning that these file types are basically us being at the mercy of what plugins decide is correct.

**Comment by chemzqm** [comment]
@QuadeMorrison It's not rename https://github.com/neoclide/coc.nvim/commit/b3604e00d133e29777591349d352ae22b2c0015c#diff-375d26229ede96ca813dae07d7bdcf8aR8, it adds support of `typescriptreact` as filetype.

`typescript.tsx` is used because https://github.com/ianks/vim-tsx/blob/master/ftdetect/typescript.vim use that as filetype.
