### ISSUE TITLE
Function/method name in statusline

### ISSUE THREAD

**Issue by robertocarta** [neoclide/coc.nvim#512]
Hi - i'm using this https://github.com/tyru/current-func-info.vim to get the current function/method name in my statusline. Would it be possible to achieve something similar with coc?

**Comment by chemzqm** [comment]
Sure, you can just query for document symbols and find the nearest function symbol, but it doesn't have params information, need to extract from the line contains that function.

**Comment by liuchengxu** [comment]
hello, @robertocarta , I have implemented this feature in [vista.vim](https://github.com/liuchengxu/vista.vim). Here is the PR waiting to be merged https://github.com/liuchengxu/vista.vim/pull/28 .

<img width="1680" alt="屏幕快照 2019-03-23 下午8 03 25" src="https://user-images.githubusercontent.com/8850248/54865892-efd37280-4da7-11e9-9970-6e761c798d99.png">

You can show the nearest method/function in the statusline as follows:

```vim
function! NearestMethodOrFunction() abort
  return exists('b:vista_nearest_method_or_function') ? b:vista_nearest_method_or_function : ''
endfunction

set statusline+=%{NearestMethodOrFunction()}
```

Also refer to https://github.com/liuchengxu/eleline.vim/pull/18.

**Comment by andersevenrud** [comment]
In case anyone uses lightline, this is how you can use the above (modified example of README in this repo):

```vim
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'cocstatus', 'readonly', 'filename', 'modified', 'vistanearest' ] ]
      \ },
      \ 'component_function': {
      \   'cocstatus': 'coc#status',
      \   'vistanearest': 'NearestMethodOrFunction'
      \ }
 \}
```

@liuchengxu Is there any way to "silently" trigger vista.vim ? Because it seems like I have to open and close it in order for this to work. If I haven't missed something really obvious that is....

**Comment by liuchengxu** [comment]
@robertocarta No way at present. That feature is also what I want, you can file an issue in vista.vim and I'll work on it when I get some time.

**Comment by andersevenrud** [comment]
@liuchengxu Thanks. I'll take the discussion to your repo.

**Comment by pyrho** [comment]
Inspired by @liuchengxu 's work on Vista I started to look into coc's code to see how to implement the feature natively in coc.

Like @chemzqm said, getting the document symbols (`navtree`) is enough since it has all the symbols for the current document including line numbers and kinds. So we can easily find which function the cursor is currently in (using something similar to the binary search @liuchengxu did in Vista.vim).

@chemzqm I'm not sure what the best way to implement this is.
I've created a new provider interface (`CurrentFunctionProvider`), that has a manager implementing the `provideCurrentFunction` from the provider interface.
That manager would call the `provideDocumentSymbols` from the `DocumentSymbolManager`.

I'm really not sure I'm going in the right direction, do you think that is the best way to implement this or can you suggest an  alternative?

Thanks again your hard work on coc!

**Comment by chemzqm** [comment]
@pyrho No need to add new provider I think, add a function like `currentFunctionSymbol` to handler and add a `CocAction` branch in `plugin.ts` to call it should be fine.

I do prefer to use tools like ctags for this instead of language server since server need time to start and parse the document, but you can always parse code by use ctags.

**Comment by alexcocinda** [comment]
If anyone needs it, this is how I added it to airline:

```vim
function! NearestMethodOrFunction() abort
  return get(b:, 'vista_nearest_method_or_function', '')
endfunction

let g:airline#extensions#default#layout = [['a', 'b', 'c'], ['x', 'z', 'warning', 'error']]

call airline#parts#define_function('nearest_method', 'NearestMethodOrFunction')
let g:airline_section_c = airline#section#create([' ','nearest_method', '()'])
autocmd VimEnter * call vista#RunForNearestMethodOrFunction()
```

**Comment by aauren** [comment]
I know that this is an old issue, so sorry for the necro-comment.

I was just going to add that with the default airline section configuration, it now contains the vista status (https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/init.vim#L268-L270):

```vim
  if !exists('g:airline_section_x')
    let g:airline_section_x = airline#section#create_right(['coc_current_function', 'bookmark', 'scrollbar', 'tagbar', 'taglist', 'vista', 'gutentags', 'gen_tags', 'omnisharp', 'grepper', 'filetype'])
  endif
```

So, all I needed to add to my vim config was a variation of the above:

```vim
augroup myairline
  autocmd VimEnter * call timer_start(2000, { tid -> execute('call vista#RunForNearestMethodOrFunction()')})
augroup END
```

Not entirely sure why, but I found that I needed a short delay before calling the `vista#RunForNearestMethodOrFunction()` function. I'm guessing it has something to do with none of the built-in vim events running after the LSP had processed the file.

**Comment by farsan-rashid** [comment]
Currently it can be done by setting let g:airline#extensions#coc#enabled = 1 in vimrc and "coc.preferences.currentFunctionSymbolAutoUpdate": true in coc-settings.json
