### ISSUE TITLE
tree-sitter syntax highlight for preview window

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc.nvim#5232]
**Is your feature request related to a problem? Please describe.**
![Screenshot_20241225_003205](https://github.com/user-attachments/assets/8d12f59e-987b-49a3-aa99-7411b16dc9fa)
preview window doesn't have syntax highlight. Because this filetype only have tree-sitter highlight, not vimSyn.

**Describe the solution you'd like**
Support tree-sitter

**Describe alternatives you've considered**

**Additional context**

**Comment by Lmills71** [comment]
Thank you.


Sent from Yahoo Mail for iPhone


On Tuesday, December 24, 2024, 8:33 AM, wzy ***@***.***> wrote:




Is your feature request related to a problem? Please describe.
Screenshot_20241225_003205.png (view on web)
preview window doesn't have syntax highlight. Because this filetype only have tree-sitter highlight, not vimSyn.

Describe the solution you'd like
Support tree-sitter

Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.

Additional context
Add any other context or screenshots about the feature request here.

**Comment by fannheyward** [comment]
`let g:coc_list_preview_filetype = 1`

This will make nvim runs `setf`. If there is tree-sitter for this filetype, the highlighting should work.

**Comment by Freed-Wu** [comment]
Why it is not default value? Is there any disadvantage?

**Comment by fannheyward** [comment]
> Is there any disadvantage?

@Freed-Wu https://github.com/neoclide/coc.nvim/issues/4674#issuecomment-1703762187
