### ISSUE TITLE
Float incorrect highlighting

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#525]
**Result from CocInfo**
vim version: NVIM v0.4.0-388-g1b6c8ea23 (master + patch)
node version: v11.11.0
coc.nvim version: 0.0.59
term: xterm-256color
platform: linux

![Screenshot_20190314_174744](https://user-images.githubusercontent.com/29133776/54394848-71c6eb80-4684-11e9-940c-1af8baaf5181.png)
![Screenshot_20190314_174726](https://user-images.githubusercontent.com/29133776/54394851-74294580-4684-11e9-9166-85ed675477e6.png)
![Screenshot_20190314_174642](https://user-images.githubusercontent.com/29133776/54394853-768b9f80-4684-11e9-924f-f11c48a05062.png)

##### Changing the size of the window can break highlighting
![Screenshot_20190314_174616](https://user-images.githubusercontent.com/29133776/54394874-886d4280-4684-11e9-8437-c020af91f419.png)
![Screenshot_20190314_174624](https://user-images.githubusercontent.com/29133776/54394876-8a370600-4684-11e9-98bd-de99bca1bc14.png)

**Comment by Avi-D-coder** [comment]
@chemzqm I'm still getting same issue. It's caused by plugins. Changing to `nvim -u NONE` from `NORC` fixes the erroneous highlights but breaks plugin provided syntaxes like rust. Coc's child nvim should not load plugins, it should only `source` the relevant sytax file from the parent runtime path. `-u NONE` drastically improves performance as well.

My other concern is that coc is spawning/killing a new nvim for each highlighted block even when vim plugins are not loaded this is a battery drain. Could the child nvim instance be reused?

Thanks for all your work

**Comment by chemzqm** [comment]
>  Could the child nvim instance be reused?

Can't get highlight corrent when reuse nvim instance, it should be killed as expected now.

**Comment by wookayin** [comment]
I also run into this issue. I found that it is due to a plugin conflict, as @Avi-D-coder mentioned: in my case, the suspect was `jedi-vim`.

With jedi-vim disabled:

![image](https://user-images.githubusercontent.com/1009873/54474787-c3c05c00-47bf-11e9-94da-2ce0d0c0f528.png)

With jedi-vim enabled:

![image](https://user-images.githubusercontent.com/1009873/54474800-e94d6580-47bf-11e9-95d2-0647bdcdd5f1.png)

I will have a look at which part of `jedi-vim` exactly is causing the issue.
