### ISSUE TITLE
Plugin is reinstalled each time :PlugUpdate is called instead of just updating it

### ISSUE THREAD

**Issue by kirillbobyrev** [neoclide/coc.nvim#566]
I noticed that calling `:PlugUpdate` always installs the plugin regardless of whether it is already installed. This takes up some extra time and looks somewhat inconsistent with the expected behavior (I would be less surprised if `:PlugInstall` would do the installation and `:PlugUpdate` would just fail if `coc.nvim` is not installed (something like `"please run :PlugInstall first"`).

LanguageClient-neovim which I used before comes with this suggested setup

```
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
```

If the plugin is not installed, `bash install.sh` will install it (even if `:PlugUpdate` was called), but if it is already installed it will only update it which seems like an elegant solution.

**Comment by chemzqm** [comment]
The problem is there's no version number with binary released file, so it's not possible to know if the release you have downloaded is outdated.
You should use `'tag': '*'` to only upgrade on new release if you don't want to build from source, the api of vim code could be changed which would introduce issues with binary release, so the approach from LanguageClient-neovim is buggy.
