### ISSUE TITLE
Incorrect incremental sync states

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#596]
**Result from CocInfo**
vim version: NVIM v0.4.0-430-g8698830cb
node version: v11.12.0
coc.nvim version: 0.0.62
term: xterm-256color
platform: linux

**Describe the bug**
This bug has been present since I started using Coc.
Diagnostics occasionally appear for buffer states that never existed in vim.
I have observed this bug with several language servers all of which support incremental sync.
After a few seconds plus inserting deleting a space diagnostics become correct.

I'll trace when I get a chance. So I know exactly what is being sent.
Is anyone else having this issue?
![Screenshot_20190326_021936](https://user-images.githubusercontent.com/29133776/54975917-0e379a80-4f6f-11e9-99c5-bf4f9add9176.png)

**Comment by chemzqm** [comment]
The diagnostics would only get refreshed on InsertLeave by  default.

**Comment by reaysawa** [comment]
It could be happening when diagnostics are not refreshed on Insert Mode. Theoretically:

1. Incomplete text ends up being sent after TextChanged or after leaving Insert Mode briefly and re-entering it again (e.g. using snippets). This results in error diagnosis after a small delay.
2. You enter Insert Mode - diagnostics don't refresh, so the error keeps lingering in there.

IIRC the document is still syncing during Insert Mode, it's just that diagnostics aren't being updated.
https://github.com/neoclide/coc.nvim/blob/master/plugin/coc.vim#L162

Due to this syncing the server could be building diagnostic analysis for incomplete states which don't exist after leaving Insert Mode. It seems like _InsertLeave_ is delegating to the same action as _TextChangedI_ so that shouldn't be a problem as far as behavior goes.

https://github.com/neoclide/coc.nvim/blob/568d1cbdc73758e1d3521141b911a5c8ca8e4437/src/handler/index.ts#L108
https://github.com/neoclide/coc.nvim/blob/568d1cbdc73758e1d3521141b911a5c8ca8e4437/src/handler/index.ts#L125

Perhaps the place to look at would be

https://github.com/neoclide/coc.nvim/blob/568d1cbdc73758e1d3521141b911a5c8ca8e4437/src/handler/index.ts#L656

and forcing another sync when **insertLeave** is true.

> Is anyone else having this issue?

I've had similar problems with RLS because it's slow, so diagnostic takes time to build and sometimes doesn't go away after InsertLeave. Unsure how to deal with it though because I don't code in Rust much.

**Comment by free-easy** [comment]
I'm facing the same issue with  [coc-tsserver](https://github.com/neoclide/coc-tsserver).

![Screenshot from 2019-04-14 20-10-27](https://user-images.githubusercontent.com/20483759/56097194-63712700-5ef1-11e9-97cd-9b6c5c767c51.png)

**Comment by chemzqm** [comment]
@free-easy looks like it's caused by slow of language server, please upload log of tsserver.

**Comment by free-easy** [comment]
Ok. When I'll encounter this problem again, I'll upload.

**Comment by suo** [comment]
I'm facing the same problem consistently with both cquery and ccls. Diagnostics will show errors on buffer states that never existed, or really old ones. These diagnostics will persist until I force a sync with `:e`. 

Here is the log from ccls when this happened, but it doesn't seem very informative: https://gist.github.com/suo/7cf1540552b71fc280b024f4b4887dd8.

This problem only started happening when I updated to the latest release, so it could have been a recently introduced regression. I don't know how to check release I was on before though :(

**Comment by escorponox** [comment]
I'm also facing this problem. Diagnostics stop refreshing randomly and I have to `:CocRestart`. I also have the feeling that this started to happen a couple of releases ago.

**Comment by iamcco** [comment]
I have meet this problem several times.

**Comment by chemzqm** [comment]
I have missed this problem for sometime, please turn on verbose output of language server and upload the output so I can know what happened.

**Comment by suo** [comment]
I rolled back to `v0.0.56` and I'm pretty sure things work (I will continue to use throughout the day to confirm). I can binary search until I find the breaking release, although it make take a few days.

**Comment by lisanhu** [comment]
I'm still having this problem, and I found an example which will consistently reproduce the problem on my machine
```
#ifndef _CHAINING_  
#define _CHAINING_                                                       
  
typedef struct ch_anchor_t {  
                                                                         
} ch_anchor_t;  
  
#endif  
```

So suppose you have a file like the above code snippet

Then you put your cursor on the line: typedef ...

Then press O to insert a line above.

Enter: /*\<cr\>\<cr\>\<cr\>\<backspace\>/
So your comment should be completed, your code will look like the snippet below. 
```
#ifndef _CHAINING_  
#define _CHAINING_                                                       
  
/**  
 *  
 */  
typedef struct ch_anchor_t {  
                                                                         
} ch_anchor_t;  
  
#endif 
```
And then you exit the insert mode using \<esc\>, you will be seeing a red mark marking the beginning of the comment. It says something about your comment is not finished correctly. However, the error message is incorrect.

The way I remove this error is to write the file and reload it using ":e" command, or using ":CocRestart"

It's not a big problem, but it's annoying.

I'm using clangd-8 BTW.

Maybe this type of comments will shadow everything afterward before it's completed, and after completing the comments, the language server will need to process a lot more new symbols that slow it down, this might be the reason why I can constantly reproduce the problem.

**Comment by iamcco** [comment]
reproduce with blow javascript code.
```
const fs = require('fs')

function test () {
}
```

Cursor on the line: `function ...`

Then press O to insert a line above.

Enter: `/*<cr><cr><cr><cr><cr><backspace>/<esc>`

then got the follow diagnostic:

<img width="600" alt="屏幕快照 2019-08-03 上午9 47 07" src="https://user-images.githubusercontent.com/5492542/62405753-07332f80-b5d4-11e9-9303-64c49748791b.png">

**Comment by chemzqm** [comment]
I can reproduce, consider open a new issue
