### ISSUE TITLE
Coc.nvim Extensions

### ISSUE THREAD

**Issue by iamrecursion** [neoclide/coc.nvim#674]
This is mainly an inquiry as to the difficulty of porting a VSCode extension to work with Coc. I'm primarily interested in porting [vscode-hie-server](https://github.com/alanz/vscode-hie-server/) as it offers some additional niceties on top of just using the Haskell IDE Engine directly as a language server. 

Along these lines, a few questions:
- In your experience, what is the usual amount of work required to port an extension from VSCode to coc?
- Are the changes usually centralised in a few files, or spread across the whole codebase? 
- What is the maintainence burden like for keeping up with ongoing changes to the VSCode extension?

**Comment by chemzqm** [comment]
> In your experience, what is the usual amount of work required to port an extension from VSCode to coc?

Should be implement features that not exists with coc and debugging.

> Are the changes usually centralised in a few files, or spread across the whole codebase?

It depends how many VSCode apis the extensions using, coc use types from `vscode-languageserver-protocol`, `vscode-uri` and coc.nvim instead of vscode.

> What is the maintainence burden like for keeping up with ongoing changes to the VSCode extension?

I get the updates from VSCode's release notes, or watch vscode extension for new release, then add the fix and/or features needed.  Not everything, since it's obvious there're a lot stuff of VSCode not implemented yet.

**Comment by iamrecursion** [comment]
Thanks for the quick response. I may give porting that extension a go at some point.
