### ISSUE TITLE
Wrong languageId passed for TeX and friends

### ISSUE THREAD

**Issue by astoff** [neoclide/coc.nvim#757]
Coc sends the wrong `languageId` parameter for LaTeX and plain TeX files. According to the LSP spec, the values should be `latex` for LaTeX and `tex` for plain, but coc (and vim) refers to these types as `tex` and `plaintex` respectively.

To reproduce, one can use the [server configuration](https://github.com/neoclide/coc.nvim/wiki/Language-servers#latex) that I recently added to the wiki.

**Comment by chemzqm** [comment]
You have to use `g:coc_filetype_map` for now.

**Comment by chemzqm** [comment]
Added to wiki page.

**Comment by valentjn** [comment]
Does “for now” mean this issue is going to be fixed eventually?

`tex` and `plaintex` are [Vim filetypes](https://neovim.io/doc/user/filetype.html), while `latex` and `tex` are [LSP language identifiers](https://microsoft.github.io/language-server-protocol/specification#textDocumentItem). Mixing those two (especially using `tex` as LSP language identifier for L<sup>A</sup>T<sub>E</sub>X files) is against the recommendations of the LSP spec. It shouldn't be the task of the user to fix this manually, as the filetype (`tex`, which means L<sup>A</sup>T<sub>E</sub>X) is correctly determined by Vim for L<sup>A</sup>T<sub>E</sub>X files.

**Comment by oblitum** [comment]
I agree. I'm for reopening/fixing.

**Comment by astoff** [comment]
FWIW, I think you should fix the `latex` case, but I would suggest keeping `plaintex` instead of `tex` as language id. It's not clear what the language id table linked above means by TeX.

Also, Digestif (which AFAIK is the only server that supports plain TeX) already understands `plaintex` and maps `tex -> latex` (because of vim), so you would break it you you mapped `plaintex -> tex`.

**Comment by valentjn** [comment]
@astoff I'll open a PR for using the language ID `latex` instead of the language ID `tex`. This would only break servers that somehow don't support `latex`, but that still support L<sup>A</sup>T<sub>E</sub>X documents via the language ID `tex`. This should be very few servers, and those could be easily fixed by adding support for the language ID `latex`, which is the LSP recommendation, anyway.
