### ISSUE TITLE
allow fallback when some LSP operations fail (show_documentation for instance)

### ISSUE THREAD

**Issue by teto** [neoclide/coc.nvim#865]
**Is your feature request related to a problem? Please describe.**
LSP servers can return underwhelming/unsatisfying results. For isntance I have trouble getting documentation from haskell-ide-engine with the recommended show_documentation
```
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
```

**Describe the solution you'd like**
I would like to modify the show_documentation function to handle `CocAction('doHover')` failures or empty results. I would like the CocAction return value to tell me if it was successful or not, and it it's always successful check for empty answers.

**Describe alternatives you've considered**
On gitter I was recommended to use coc#util#echo_line() but that displays the msg without allowing comparisons.

Some pseudocode
```
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')

	if &ft == "haskell"
		let result=coc#util#echo_line()
		if result ==  '[coc.nvim] No definition found.'
			echom "haskell fallback, invoke Keywordprg or hoogle for instance"
		endif

	endif
  endif
endfunction
```

**Comment by teto** [comment]
fantastic . Do I need to wait for another release to benefit from it ? I use the binary from https://github.com/neoclide/coc.nvim/releases, not sure how typescript works...

**Comment by chemzqm** [comment]
Yes, release not updated very frequently.

**Comment by ShikChen** [comment]
Is there a way to suppress the error message such as `[coc.nvim] Definition not found`? It feels like that the error message is echoed asynchronously, so the message is overridden by coc even if I echoed some other message after `CocAction()`. POC from my `init.nvim`:

``` vim
function! s:goto_definition()
  if CocAction('jumpDefinition')
    return v:true
  endif
  echom "Failed to find definition using coc.nvim, fall back to tags."
  execute "normal \<C-]>"
endfunction

nmap <silent> <leader>d :call <SID>goto_definition()<CR>
```

The message is overridden by coc, which can be confirmed by the output of `:messages`:

```
Failed to find definition using coc.nvim, fall back to tags.
[coc.nvim] Definition not found
Press ENTER or type command to continue
```

**Comment by chemzqm** [comment]
It's not async when using CocAction, but neovim has bug with silent of rpcrequest https://github.com/neovim/neovim/issues/10310

**Comment by ShikChen** [comment]
Thanks for the super fast reply!

I just took a quick glance of the code path of `CocAction()`, and I think the underlying problem is still async. Although the outer `rpcrequest()` for `CocAction()` is blocking, the implementation of `CocAction()` would echo the message in an async way. The code path:

https://github.com/neoclide/coc.nvim/blob/6ec65c9613a5be3d6aba122f2eb33ad44b53e14a/src/handler/index.ts#L276-L285

https://github.com/neoclide/coc.nvim/blob/6ec65c9613a5be3d6aba122f2eb33ad44b53e14a/src/handler/index.ts#L991-L997

...(snip)...

https://github.com/neoclide/coc.nvim/blob/6ec65c9613a5be3d6aba122f2eb33ad44b53e14a/src/util/index.ts#L41-L43

The `nvim.callTimer()` here would send the command in [an async way](https://github.com/neoclide/neovim/blob/986032c1af5fc363ef76db2b95e6857671099e09/src/api/Neovim.ts#L253-L268).
