### ISSUE TITLE
Automatic language detection or reminder for extensions?

### ISSUE THREAD

**Issue by Trollwut** [neoclide/coc.nvim#887]
Hello folks!

I guess everyone knows about `deoplete`. The cool stuff about this package is, that it automatically detects which file extension is being opened and loads the fitting plugin for it.

Now I'm currently switching to coc.vim (and it's awesome), but everytime I open a file, I have to think about, if I have the extentions installed for it.

Is something planned like a reminder that there would be an extension available for the opened file type?

**Comment by chemzqm** [comment]
`deoplete` doesn't have feature for install required completion plugin, it's your other vim plugin have completion source for deoplete,  coc.nvim have that supported too.

Will not add feature which prompt user of available extension, since you may prefer to use configuration instead or there could be many alternatives, you have to find out them.

**Comment by Trollwut** [comment]
omg, I mistook `deoplete` for `polyglot`. And the latter totally works with `coc.vim`.

Installing linters should be done manually by the user. I am totally on your side.

Sorry, big brainfart.
