### ISSUE TITLE
Tree view feature mimicking issue 371 from vim-ls

### ISSUE THREAD

**Issue by lanza** [neoclide/coc.nvim#927]
![image](https://user-images.githubusercontent.com/12656790/60388984-86ca5d80-9a6e-11e9-8cfc-8705dc6709f4.png)

This is from lsp-mode and ccls. Somebody requested similar functionality from [vim-lsp](https://github.com/prabirshrestha/vim-lsp/issues/371) a few months ago and some of the guys working on it have started working on similar functionality. ([here](https://github.com/m-pilia/vim-ccls) and [here](https://github.com/m-pilia/vim-yggdrasil)). I think this would be a fantastic feature to add to coc.nvim.

**Comment by Avi-D-coder** [comment]
Have you seen vista.vim?

**Comment by m-pilia** [comment]
Not sure since I do not use it, but I think vista.vim does not support call/inheritance hierarchies.

Limited to ccls, the [vim-ccls](https://github.com/m-pilia/vim-ccls) plugin works on top of coc.nvim, and should provide a call hierarchy view that should be similar to [lsp-mode](https://github.com/emacs-lsp/lsp-mode)/[emacs-ccls](https://github.com/MaskRay/emacs-ccls). However, note that ccls uses a non-standard method for call hierarchies, that is not part of the LSP API.

There is an [open issue in Microsoft LSP](https://github.com/microsoft/language-server-protocol/issues/468) to add a `textDocument/callHierarchy` method. I think it would be nice if coc.nvim could add support for this method in the future, even though I am not sure it is currently implemented by any language server.

**Comment by hoschi** [comment]
Sounds similiar as https://github.com/neoclide/coc.nvim/issues/1649

**Comment by chemzqm** [comment]
Tree view support with API and features like VSCode is WIP, checkout #3234
